.TH "lsevents_listener_struct" 3 "Thu Jun 19 2014" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsevents_listener_struct \- 
.PP
Linked list of event listeners\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlsevents_listener_struct\fP * \fBnext\fP"
.br
.RI "\fINext listener\&. \fP"
.ti -1c
.RI "char * \fBraw_regexp\fP"
.br
.RI "\fIthe original string sent to us \fP"
.ti -1c
.RI "regex_t \fBre\fP"
.br
.RI "\fIregular expression representing listened for events \fP"
.ti -1c
.RI "void(* \fBcb\fP )(char *)"
.br
.RI "\fIcall back function \fP"
.in -1c
.SH "Detailed Description"
.PP 
Linked list of event listeners\&. 
.PP
Definition at line 35 of file lsevents\&.c\&.
.SH "Field Documentation"
.PP 
.SS "void(* lsevents_listener_struct::cb)(char *)"

.PP
call back function 
.PP
Definition at line 39 of file lsevents\&.c\&.
.SS "struct \fBlsevents_listener_struct\fP* lsevents_listener_struct::next"

.PP
Next listener\&. 
.PP
Definition at line 36 of file lsevents\&.c\&.
.SS "char* lsevents_listener_struct::raw_regexp"

.PP
the original string sent to us 
.PP
Definition at line 37 of file lsevents\&.c\&.
.SS "regex_t lsevents_listener_struct::re"

.PP
regular expression representing listened for events 
.PP
Definition at line 38 of file lsevents\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
