.TH "iniParser" 3 "Wed May 22 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iniParser \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBiniParser\fP"
.br
.RI "\fIThis program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBip\fP \fBiniParser\fP( '21-ID-D/microdiff_pref\&.ini')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple iniParser\&.ip \fBiniParser\fP( '21-ID-D/microdiff_pref\&.ini')"

.PP
Definition at line 104 of file iniParser\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
