.TH "lsevents_listeners_strcut" 3 "11 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsevents_listeners_strcut \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct lsevents_listeners_struct * \fBnext\fP"
.br
.RI "\fINext listener. \fP"
.ti -1c
.RI "char \fBevent\fP [LSEVENTS_EVENT_LENGTH]"
.br
.RI "\fIname of the event we are listening for \fP"
.ti -1c
.RI "void(* \fBcb\fP )(char *)"
.br
.RI "\fIcall back function \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file lsevents.c.
.SH "Field Documentation"
.PP 
.SS "void(* \fBlsevents_listeners_strcut::cb\fP)(char *)"
.PP
call back function 
.SS "char \fBlsevents_listeners_strcut::event\fP[LSEVENTS_EVENT_LENGTH]"
.PP
name of the event we are listening for 
.PP
Definition at line 24 of file lsevents.c.
.SS "struct lsevents_listeners_struct* \fBlsevents_listeners_strcut::next\fP\fC [read]\fP"
.PP
Next listener. 
.PP
Definition at line 23 of file lsevents.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
