.TH "lsevents_queue_struct" 3 "Sun Dec 16 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsevents_queue_struct \- 
.PP
Storage definition for the events\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBevent\fP [\fBLSEVENTS_EVENT_LENGTH\fP]"
.br
.RI "\fIname of the event \fP"
.in -1c
.SH "Detailed Description"
.PP 
Storage definition for the events\&. 

Just a string for now\&. Perhaps one day we'll succumb to the temptation to add an argument or two\&. 
.PP
Definition at line 17 of file lsevents\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char lsevents_queue_struct::event[\fBLSEVENTS_EVENT_LENGTH\fP]"

.PP
name of the event 
.PP
Definition at line 18 of file lsevents\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
