.TH "lsevents_listener_struct" 3 "Wed Nov 14 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsevents_listener_struct \- 
.PP
Linked list of event listeners\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlsevents_listener_struct\fP * \fBnext\fP"
.br
.RI "\fINext listener\&. \fP"
.ti -1c
.RI "char \fBevent\fP [\fBLSEVENTS_EVENT_LENGTH\fP]"
.br
.RI "\fIname of the event we are listening for \fP"
.ti -1c
.RI "void(* \fBcb\fP )(char *)"
.br
.RI "\fIcall back function \fP"
.in -1c
.SH "Detailed Description"
.PP 
Linked list of event listeners\&. 
.PP
Definition at line 27 of file lsevents\&.c\&.
.SH "Field Documentation"
.PP 
.SS "void(* lsevents_listener_struct::cb)(char *)"

.PP
call back function 
.PP
Definition at line 30 of file lsevents\&.c\&.
.SS "char lsevents_listener_struct::event[\fBLSEVENTS_EVENT_LENGTH\fP]"

.PP
name of the event we are listening for 
.PP
Definition at line 29 of file lsevents\&.c\&.
.SS "struct \fBlsevents_listener_struct\fP* lsevents_listener_struct::next"

.PP
Next listener\&. 
.PP
Definition at line 28 of file lsevents\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
