.TH "lsevents_queue_struct" 3 "14 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsevents_queue_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBevent\fP [LSEVENTS_EVENT_LENGTH]"
.br
.RI "\fIname of the event \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file lsevents.c.
.SH "Field Documentation"
.PP 
.SS "char \fBlsevents_queue_struct::event\fP[LSEVENTS_EVENT_LENGTH]"
.PP
name of the event 
.PP
Definition at line 13 of file lsevents.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
