.TH "lsevents_callbacks_struct" 3 "Thu Jun 19 2014" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsevents_callbacks_struct \- 
.PP
lsevents linked list of callbacks for each event  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlsevents_callbacks_struct\fP * \fBnext\fP"
.br
.ti -1c
.RI "void(* \fBcb\fP )(char *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
lsevents linked list of callbacks for each event 
.PP
Definition at line 46 of file lsevents\&.c\&.
.SH "Field Documentation"
.PP 
.SS "void(* lsevents_callbacks_struct::cb)(char *)"

.PP
Definition at line 48 of file lsevents\&.c\&.
.SS "struct \fBlsevents_callbacks_struct\fP* lsevents_callbacks_struct::next"

.PP
Definition at line 47 of file lsevents\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
