.TH "lsevents_event_names_struct" 3 "Wed May 22 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsevents_event_names_struct \- 
.PP
linked list of all the event names used to regenerate the hash table  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct 
.br
\fBlsevents_event_names_struct\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBevent\fP"
.br
.ti -1c
.RI "\fBlsevents_callbacks_t\fP * \fBcbl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
linked list of all the event names used to regenerate the hash table 
.PP
Definition at line 55 of file lsevents\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBlsevents_callbacks_t\fP* lsevents_event_names_struct::cbl"

.PP
Definition at line 58 of file lsevents\&.c\&.
.SS "char* lsevents_event_names_struct::event"

.PP
Definition at line 57 of file lsevents\&.c\&.
.SS "struct \fBlsevents_event_names_struct\fP* lsevents_event_names_struct::next"

.PP
Definition at line 56 of file lsevents\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
