.TH "lsevents_listener_struct" 3 "14 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsevents_listener_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlsevents_listener_struct\fP * \fBnext\fP"
.br
.RI "\fINext listener. \fP"
.ti -1c
.RI "char \fBevent\fP [LSEVENTS_EVENT_LENGTH]"
.br
.RI "\fIname of the event we are listening for \fP"
.ti -1c
.RI "void(* \fBcb\fP )(char *)"
.br
.RI "\fIcall back function \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file lsevents.c.
.SH "Field Documentation"
.PP 
.SS "void(* \fBlsevents_listener_struct::cb\fP)(char *)"
.PP
call back function 
.SS "char \fBlsevents_listener_struct::event\fP[LSEVENTS_EVENT_LENGTH]"
.PP
name of the event we are listening for 
.PP
Definition at line 22 of file lsevents.c.
.SS "struct \fBlsevents_listener_struct\fP* \fBlsevents_listener_struct::next\fP\fC [read]\fP"
.PP
Next listener. 
.PP
Definition at line 21 of file lsevents.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
