.TH "lskvs_kvs_struct" 3 "14 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lskvs_kvs_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlskvs_kvs_struct\fP * \fBnext\fP"
.br
.RI "\fIthe next kvpair \fP"
.ti -1c
.RI "pthread_rwlock_t \fBl\fP"
.br
.RI "\fIour lock \fP"
.ti -1c
.RI "char * \fBk\fP"
.br
.RI "\fIthe key \fP"
.ti -1c
.RI "char * \fBv\fP"
.br
.RI "\fIthe value \fP"
.ti -1c
.RI "int \fBvl\fP"
.br
.RI "\fIthe length of the calloced v \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file lskvs.c.
.SH "Field Documentation"
.PP 
.SS "char* \fBlskvs_kvs_struct::k\fP"
.PP
the key 
.PP
Definition at line 20 of file lskvs.c.
.SS "pthread_rwlock_t \fBlskvs_kvs_struct::l\fP"
.PP
our lock 
.PP
Definition at line 19 of file lskvs.c.
.SS "struct \fBlskvs_kvs_struct\fP* \fBlskvs_kvs_struct::next\fP\fC [read]\fP"
.PP
the next kvpair 
.PP
Definition at line 18 of file lskvs.c.
.SS "char* \fBlskvs_kvs_struct::v\fP"
.PP
the value 
.PP
Definition at line 21 of file lskvs.c.
.SS "int \fBlskvs_kvs_struct::vl\fP"
.PP
the length of the calloced v 
.PP
Definition at line 22 of file lskvs.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
