.TH "lskvs_kvs_list_struct" 3 "Thu Nov 15 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lskvs_kvs_list_struct \- 
.PP
A second linked list type to handle private lists of KVs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlskvs_kvs_list_struct\fP * \fBnext\fP"
.br
.RI "\fInext item \fP"
.ti -1c
.RI "\fBlskvs_kvs_t\fP * \fBkvs\fP"
.br
.RI "\fIthe KV \fP"
.in -1c
.SH "Detailed Description"
.PP 
A second linked list type to handle private lists of KVs\&. 

Developed to support lists of preset motor positions\&. 
.PP
Definition at line 84 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBlskvs_kvs_t\fP* lskvs_kvs_list_struct::kvs"

.PP
the KV 
.PP
Definition at line 86 of file pgpmac\&.h\&.
.SS "struct \fBlskvs_kvs_list_struct\fP* lskvs_kvs_list_struct::next"

.PP
next item 
.PP
Definition at line 85 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
