.TH "lskvs_kvs_struct" 3 "Thu Nov 29 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lskvs_kvs_struct \- 
.PP
Storage for the key value pairs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlskvs_kvs_struct\fP * \fBnext\fP"
.br
.RI "\fIthe next kvpair \fP"
.ti -1c
.RI "pthread_rwlock_t \fBl\fP"
.br
.RI "\fIour lock \fP"
.ti -1c
.RI "char * \fBk\fP"
.br
.RI "\fIthe key \fP"
.ti -1c
.RI "char * \fBv\fP"
.br
.RI "\fIthe value \fP"
.ti -1c
.RI "int \fBvl\fP"
.br
.RI "\fIthe length of the calloced v \fP"
.in -1c
.SH "Detailed Description"
.PP 
Storage for the key value pairs\&. 

the k's and v's are strings and to keep the memory management less crazy we'll calloc some space for these strings and only free and re-calloc if we need more space later\&. Only the values are ever going to be resized\&. 
.PP
Definition at line 73 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* lskvs_kvs_struct::k"

.PP
the key 
.PP
Definition at line 76 of file pgpmac\&.h\&.
.SS "pthread_rwlock_t lskvs_kvs_struct::l"

.PP
our lock 
.PP
Definition at line 75 of file pgpmac\&.h\&.
.SS "struct \fBlskvs_kvs_struct\fP* lskvs_kvs_struct::next"

.PP
the next kvpair 
.PP
Definition at line 74 of file pgpmac\&.h\&.
.SS "char* lskvs_kvs_struct::v"

.PP
the value 
.PP
Definition at line 77 of file pgpmac\&.h\&.
.SS "int lskvs_kvs_struct::vl"

.PP
the length of the calloced v 
.PP
Definition at line 78 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
