.TH "lslogging_queue_struct" 3 "Tue Dec 18 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lslogging_queue_struct \- 
.PP
Our log object: time and message\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct timespec \fBltime\fP"
.br
.RI "\fItime stamp: set when queued \fP"
.ti -1c
.RI "char \fBlmsg\fP [\fBLSLOGGING_MSG_LENGTH\fP]"
.br
.RI "\fIour message, truncated if too long \fP"
.in -1c
.SH "Detailed Description"
.PP 
Our log object: time and message\&. 
.PP
Definition at line 24 of file lslogging\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char lslogging_queue_struct::lmsg[\fBLSLOGGING_MSG_LENGTH\fP]"

.PP
our message, truncated if too long 
.PP
Definition at line 26 of file lslogging\&.c\&.
.SS "struct timespec lslogging_queue_struct::ltime"

.PP
time stamp: set when queued 
.PP
Definition at line 25 of file lslogging\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
