.TH "lslogging.c" 3 "14 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lslogging.c \- 
.PP
Logs messages to a file.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pgpmac.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBlslogging_queue_struct\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLSLOGGING_FILE_NAME\fP   '/tmp/pgpmac.log'"
.br
.ti -1c
.RI "#define \fBLSLOGGING_MSG_LENGTH\fP   256"
.br
.ti -1c
.RI "#define \fBLSLOGGING_QUEUE_LENGTH\fP   256"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBlslogging_queue_struct\fP \fBlslogging_queue_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlslogging_init\fP ()"
.br
.ti -1c
.RI "void \fBlslogging_log_message\fP (char *fmt,...)"
.br
.ti -1c
.RI "void * \fBlslogging_worker\fP (void *dummy)"
.br
.ti -1c
.RI "void \fBlslogging_run\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static pthread_t \fBlslogging_thread\fP"
.br
.ti -1c
.RI "static pthread_mutex_t \fBlslogging_mutex\fP"
.br
.ti -1c
.RI "static pthread_cond_t \fBlslogging_cond\fP"
.br
.ti -1c
.RI "static FILE * \fBlslogging_file\fP"
.br
.ti -1c
.RI "static \fBlslogging_queue_t\fP \fBlslogging_queue\fP [LSLOGGING_QUEUE_LENGTH]"
.br
.ti -1c
.RI "static unsigned int \fBlslogging_on\fP = 0"
.br
.RI "\fInext location to add to the queue \fP"
.ti -1c
.RI "static unsigned int \fBlslogging_off\fP = 0"
.br
.RI "\fInext location to remove from the queue \fP"
.in -1c
.SH "Detailed Description"
.PP 
Logs messages to a file. 

\fBDate:\fP
.RS 4
2012 
.RE
.PP
\fBAuthor:\fP
.RS 4
Keith Brister  All Rights Reserved 
.RE
.PP

.PP
Definition in file \fBlslogging.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define LSLOGGING_FILE_NAME   '/tmp/pgpmac.log'"
.PP
Definition at line 15 of file lslogging.c.
.SS "#define LSLOGGING_MSG_LENGTH   256"
.PP
Definition at line 18 of file lslogging.c.
.SS "#define LSLOGGING_QUEUE_LENGTH   256"
.PP
Definition at line 24 of file lslogging.c.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBlslogging_queue_struct\fP  \fBlslogging_queue_t\fP"
.SH "Function Documentation"
.PP 
.SS "void lslogging_init ()"
.PP
Definition at line 30 of file lslogging.c.
.PP
.nf
30                       {
31   pthread_mutex_init( &lslogging_mutex, NULL);
32   pthread_cond_init(  &lslogging_cond, NULL);
33 
34   lslogging_file = fopen( LSLOGGING_FILE_NAME, 'w');
35 }
.fi
.SS "void lslogging_log_message (char * fmt,  ...)"
.PP
Definition at line 37 of file lslogging.c.
.PP
.nf
37                                             {
38   char msg[LSLOGGING_MSG_LENGTH];
39   struct timespec theTime;
40   va_list arg_ptr;
41 
42   clock_gettime( CLOCK_REALTIME, &theTime);
43 
44   va_start( arg_ptr, fmt);
45   vsnprintf( msg, sizeof(msg)-1, fmt, arg_ptr);
46   va_end( arg_ptr);
47   msg[sizeof(msg)-1]=0;
48 
49   pthread_mutex_lock( &lslogging_mutex);
50   
51   strncpy( lslogging_queue[lslogging_on].lmsg, msg, LSLOGGING_MSG_LENGTH - 1);
52   lslogging_queue[lslogging_on].lmsg[LSLOGGING_MSG_LENGTH-1] = 0;
53   
54   memcpy( &(lslogging_queue[lslogging_on].ltime), &theTime, sizeof(theTime));
55 
56   lslogging_on++;
57   lslogging_on %= LSLOGGING_QUEUE_LENGTH;
58 
59   pthread_cond_signal(  &lslogging_cond);
60   pthread_mutex_unlock( &lslogging_mutex);
61   
62 }
.fi
.SS "void lslogging_run ()"
.PP
Definition at line 92 of file lslogging.c.
.PP
.nf
92                      {
93   pthread_create( &lslogging_thread, NULL, &lslogging_worker, NULL);
94   lslogging_log_message( 'Start up');
95 }
.fi
.SS "void* lslogging_worker (void * dummy)"\fBParameters:\fP
.RS 4
\fIdummy\fP Required by protocol but unused 
.RE
.PP

.PP
Definition at line 64 of file lslogging.c.
.PP
.nf
66                         {
67 
68 
69   struct tm coarsetime;
70   char tstr[64];
71   unsigned int msecs;
72 
73   pthread_mutex_lock( &lslogging_mutex);
74 
75   while( 1) {
76     while( lslogging_on == lslogging_off) {
77       pthread_cond_wait( &lslogging_cond, &lslogging_mutex);
78     }
79     
80     localtime_r( &(lslogging_queue[lslogging_off].ltime.tv_sec), &coarsetime);
81     strftime( tstr, sizeof(tstr)-1, '%Y-%m-%d %H:%M:%S', &coarsetime);
82     tstr[sizeof(tstr)-1] = 0;
83     msecs = lslogging_queue[lslogging_off].ltime.tv_nsec / 1000000;
84     fprintf( lslogging_file, '%s.%.03u  %s\n', tstr, msecs, lslogging_queue[lslogging_off].lmsg);
85     fflush( lslogging_file);
86 
87     lslogging_off++;
88     lslogging_off %= LSLOGGING_QUEUE_LENGTH;
89   }
90 }
.fi
.SH "Variable Documentation"
.PP 
.SS "pthread_cond_t \fBlslogging_cond\fP\fC [static]\fP"
.PP
Definition at line 12 of file lslogging.c.
.SS "FILE* \fBlslogging_file\fP\fC [static]\fP"
.PP
Definition at line 16 of file lslogging.c.
.SS "pthread_mutex_t \fBlslogging_mutex\fP\fC [static]\fP"
.PP
Definition at line 11 of file lslogging.c.
.SS "unsigned int \fBlslogging_off\fP = 0\fC [static]\fP"
.PP
next location to remove from the queue 
.PP
Definition at line 28 of file lslogging.c.
.SS "unsigned int \fBlslogging_on\fP = 0\fC [static]\fP"
.PP
next location to add to the queue 
.PP
Definition at line 27 of file lslogging.c.
.SS "\fBlslogging_queue_t\fP \fBlslogging_queue\fP[LSLOGGING_QUEUE_LENGTH]\fC [static]\fP"
.PP
Definition at line 25 of file lslogging.c.
.SS "pthread_t \fBlslogging_thread\fP\fC [static]\fP"
.PP
Definition at line 10 of file lslogging.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
