.TH "lslogging_queue_struct" 3 "14 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lslogging_queue_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct timespec \fBltime\fP"
.br
.RI "\fItime stamp: set when queued \fP"
.ti -1c
.RI "char \fBlmsg\fP [LSLOGGING_MSG_LENGTH]"
.br
.RI "\fIour message, truncated if too long \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file lslogging.c.
.SH "Field Documentation"
.PP 
.SS "char \fBlslogging_queue_struct::lmsg\fP[LSLOGGING_MSG_LENGTH]"
.PP
our message, truncated if too long 
.PP
Definition at line 21 of file lslogging.c.
.SS "struct timespec \fBlslogging_queue_struct::ltime\fP\fC [read]\fP"
.PP
time stamp: set when queued 
.PP
Definition at line 20 of file lslogging.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
