.TH "lspg_getcenter_struct" 3 "14 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_getcenter_struct \- 
.PP
Storage for getcenter query Used for the md2 ROTATE command that generates the centering movies.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "\fIdon't let the threads collide! \fP"
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.RI "\fIprovides signaling for when the query is done \fP"
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.RI "\fIused with condition \fP"
.ti -1c
.RI "int \fBno_rows_returned\fP"
.br
.RI "\fIflag in case no centering information was forthcoming \fP"
.ti -1c
.RI "int \fBzoom\fP"
.br
.RI "\fIthe next zoom level to go to before taking the next movie \fP"
.ti -1c
.RI "int \fBzoom_isnull\fP"
.br
.ti -1c
.RI "double \fBdcx\fP"
.br
.RI "\fIcenter x change \fP"
.ti -1c
.RI "int \fBdcx_isnull\fP"
.br
.ti -1c
.RI "double \fBdcy\fP"
.br
.RI "\fIcenter y change \fP"
.ti -1c
.RI "int \fBdcy_isnull\fP"
.br
.ti -1c
.RI "double \fBdax\fP"
.br
.RI "\fIalignment x change \fP"
.ti -1c
.RI "int \fBdax_isnull\fP"
.br
.ti -1c
.RI "double \fBday\fP"
.br
.RI "\fIalignment y change \fP"
.ti -1c
.RI "int \fBday_isnull\fP"
.br
.ti -1c
.RI "double \fBdaz\fP"
.br
.RI "\fIalignment z change \fP"
.ti -1c
.RI "int \fBdaz_isnull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Storage for getcenter query Used for the md2 ROTATE command that generates the centering movies. 
.PP
Definition at line 119 of file pgpmac.h.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t \fBlspg_getcenter_struct::cond\fP"
.PP
provides signaling for when the query is done 
.PP
Definition at line 121 of file pgpmac.h.
.SS "double \fBlspg_getcenter_struct::dax\fP"
.PP
alignment x change 
.PP
Definition at line 134 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::dax_isnull\fP"
.PP
Definition at line 135 of file pgpmac.h.
.SS "double \fBlspg_getcenter_struct::day\fP"
.PP
alignment y change 
.PP
Definition at line 137 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::day_isnull\fP"
.PP
Definition at line 138 of file pgpmac.h.
.SS "double \fBlspg_getcenter_struct::daz\fP"
.PP
alignment z change 
.PP
Definition at line 140 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::daz_isnull\fP"
.PP
Definition at line 141 of file pgpmac.h.
.SS "double \fBlspg_getcenter_struct::dcx\fP"
.PP
center x change 
.PP
Definition at line 128 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::dcx_isnull\fP"
.PP
Definition at line 129 of file pgpmac.h.
.SS "double \fBlspg_getcenter_struct::dcy\fP"
.PP
center y change 
.PP
Definition at line 131 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::dcy_isnull\fP"
.PP
Definition at line 132 of file pgpmac.h.
.SS "pthread_mutex_t \fBlspg_getcenter_struct::mutex\fP"
.PP
don't let the threads collide! 
.PP
Definition at line 120 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::new_value_ready\fP"
.PP
used with condition 
.PP
Definition at line 122 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::no_rows_returned\fP"
.PP
flag in case no centering information was forthcoming 
.PP
Definition at line 123 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::zoom\fP"
.PP
the next zoom level to go to before taking the next movie 
.PP
Definition at line 125 of file pgpmac.h.
.SS "int \fBlspg_getcenter_struct::zoom_isnull\fP"
.PP
Definition at line 126 of file pgpmac.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
