.TH "lspg_seq_run_prep_struct" 3 "14 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_seq_run_prep_struct \- 
.PP
Data collection running object.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data collection running object. 
.PP
Definition at line 916 of file lspg.c.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t \fBlspg_seq_run_prep_struct::cond\fP"
.PP
Definition at line 918 of file lspg.c.
.SS "pthread_mutex_t \fBlspg_seq_run_prep_struct::mutex\fP"
.PP
Definition at line 917 of file lspg.c.
.SS "int \fBlspg_seq_run_prep_struct::new_value_ready\fP"
.PP
Definition at line 919 of file lspg.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
