.TH "lspg_wait_for_detector_struct" 3 "Fri Nov 16 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_wait_for_detector_struct \- 
.PP
Object that implements detector / spindle timing We use database locks for exposure control and this implements the md2 portion of this handshake\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object that implements detector / spindle timing We use database locks for exposure control and this implements the md2 portion of this handshake\&. 
.PP
Definition at line 734 of file lspg\&.c\&.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t lspg_wait_for_detector_struct::cond"

.PP
Definition at line 736 of file lspg\&.c\&.
.SS "pthread_mutex_t lspg_wait_for_detector_struct::mutex"

.PP
Definition at line 735 of file lspg\&.c\&.
.SS "int lspg_wait_for_detector_struct::new_value_ready"

.PP
Definition at line 737 of file lspg\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
