.TH "lspg_demandairrights_struct" 3 "Thu Jun 19 2014" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_demandairrights_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.ti -1c
.RI "int \fBquery_error\fP"
.br
.RI "\fI0 is OK, 1 is postgres complained\&. Note current implemention automatically logs the error \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 210 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t lspg_demandairrights_struct::cond"

.PP
Definition at line 212 of file pgpmac\&.h\&.
.SS "pthread_mutex_t lspg_demandairrights_struct::mutex"

.PP
Definition at line 211 of file pgpmac\&.h\&.
.SS "int lspg_demandairrights_struct::new_value_ready"

.PP
Definition at line 213 of file pgpmac\&.h\&.
.SS "int lspg_demandairrights_struct::query_error"

.PP
0 is OK, 1 is postgres complained\&. Note current implemention automatically logs the error 
.PP
Definition at line 214 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
