.TH "lspg_nextsample_struct" 3 "Fri May 23 2014" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_nextsample_struct \- 
.PP
Returns the next sample number Just a 32 bit int (Ha!, take that, nextshot!)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "\fIOur mutex\&. \fP"
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.RI "\fIOur condition\&. \fP"
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.RI "\fIflag for our condition \fP"
.ti -1c
.RI "int \fBquery_error\fP"
.br
.RI "\fI0 is OK, 1 is postgres complained\&. Note current implemention automatically logs the error \fP"
.ti -1c
.RI "int \fBno_rows_returned\fP"
.br
.RI "\fIjust in case, though this query should always return an integer, perhaps 0 \fP"
.ti -1c
.RI "unsigned int \fBnextsample\fP"
.br
.RI "\fIsample number (4 8-bit segments: station, dewar (lid), puck, and position in the puck) \fP"
.ti -1c
.RI "int \fBnextsample_isnull\fP"
.br
.RI "\fIshouldn't ever be set, but if we change the logic of this call in PG then we are ready for it here\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Returns the next sample number Just a 32 bit int (Ha!, take that, nextshot!) 
.PP
Definition at line 276 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t lspg_nextsample_struct::cond"

.PP
Our condition\&. 
.PP
Definition at line 278 of file pgpmac\&.h\&.
.SS "pthread_mutex_t lspg_nextsample_struct::mutex"

.PP
Our mutex\&. 
.PP
Definition at line 277 of file pgpmac\&.h\&.
.SS "int lspg_nextsample_struct::new_value_ready"

.PP
flag for our condition 
.PP
Definition at line 279 of file pgpmac\&.h\&.
.SS "unsigned int lspg_nextsample_struct::nextsample"

.PP
sample number (4 8-bit segments: station, dewar (lid), puck, and position in the puck) 
.PP
Definition at line 283 of file pgpmac\&.h\&.
.SS "int lspg_nextsample_struct::nextsample_isnull"

.PP
shouldn't ever be set, but if we change the logic of this call in PG then we are ready for it here\&. 
.PP
Definition at line 284 of file pgpmac\&.h\&.
.SS "int lspg_nextsample_struct::no_rows_returned"

.PP
just in case, though this query should always return an integer, perhaps 0 
.PP
Definition at line 281 of file pgpmac\&.h\&.
.SS "int lspg_nextsample_struct::query_error"

.PP
0 is OK, 1 is postgres complained\&. Note current implemention automatically logs the error 
.PP
Definition at line 280 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
