.TH "lspg_nextsample_struct" 3 "Sun Feb 17 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_nextsample_struct \- 
.PP
Returns the next sample number Just a 32 bit int (Ha!, take that, nextshot!)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "\fIOur mutex\&. \fP"
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.RI "\fIOur condition\&. \fP"
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.RI "\fIflag for our condition \fP"
.ti -1c
.RI "int \fBno_rows_returned\fP"
.br
.RI "\fIjust in case, though this query should always return an integer, perhaps 0 \fP"
.ti -1c
.RI "unsigned int \fBnextsample\fP"
.br
.RI "\fIsample number (4 8-bit segments: station, dewar (lid), puck, and position in the puck) \fP"
.ti -1c
.RI "int \fBnextsample_isnull\fP"
.br
.RI "\fIshouldn't ever be set, but if we change the logic of this call in PG then we are ready for it here\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Returns the next sample number Just a 32 bit int (Ha!, take that, nextshot!) 
.PP
Definition at line 261 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t lspg_nextsample_struct::cond"

.PP
Our condition\&. 
.PP
Definition at line 263 of file pgpmac\&.h\&.
.SS "pthread_mutex_t lspg_nextsample_struct::mutex"

.PP
Our mutex\&. 
.PP
Definition at line 262 of file pgpmac\&.h\&.
.SS "int lspg_nextsample_struct::new_value_ready"

.PP
flag for our condition 
.PP
Definition at line 264 of file pgpmac\&.h\&.
.SS "unsigned int lspg_nextsample_struct::nextsample"

.PP
sample number (4 8-bit segments: station, dewar (lid), puck, and position in the puck) 
.PP
Definition at line 267 of file pgpmac\&.h\&.
.SS "int lspg_nextsample_struct::nextsample_isnull"

.PP
shouldn't ever be set, but if we change the logic of this call in PG then we are ready for it here\&. 
.PP
Definition at line 268 of file pgpmac\&.h\&.
.SS "int lspg_nextsample_struct::no_rows_returned"

.PP
just in case, though this query should always return an integer, perhaps 0 
.PP
Definition at line 265 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
