.TH "lspg_lock_detector_struct" 3 "Sun Dec 16 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_lock_detector_struct \- 
.PP
lock detector object Implements detector lock for exposure control  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
lock detector object Implements detector lock for exposure control 
.PP
Definition at line 694 of file lspg\&.c\&.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t lspg_lock_detector_struct::cond"

.PP
Definition at line 696 of file lspg\&.c\&.
.SS "pthread_mutex_t lspg_lock_detector_struct::mutex"

.PP
Definition at line 695 of file lspg\&.c\&.
.SS "int lspg_lock_detector_struct::new_value_ready"

.PP
Definition at line 697 of file lspg\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
