.TH "lspg_getcenter_struct" 3 "Fri Dec 14 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_getcenter_struct \- 
.PP
Storage for getcenter query Used for the md2 ROTATE command that generates the centering movies\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "\fIdon't let the threads collide! \fP"
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.RI "\fIprovides signaling for when the query is done \fP"
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.RI "\fIused with condition \fP"
.ti -1c
.RI "int \fBno_rows_returned\fP"
.br
.RI "\fIflag in case no centering information was forthcoming \fP"
.ti -1c
.RI "int \fBzoom\fP"
.br
.RI "\fIthe next zoom level to go to before taking the next movie \fP"
.ti -1c
.RI "int \fBzoom_isnull\fP"
.br
.ti -1c
.RI "double \fBdcx\fP"
.br
.RI "\fIcenter x change \fP"
.ti -1c
.RI "int \fBdcx_isnull\fP"
.br
.ti -1c
.RI "double \fBdcy\fP"
.br
.RI "\fIcenter y change \fP"
.ti -1c
.RI "int \fBdcy_isnull\fP"
.br
.ti -1c
.RI "double \fBdax\fP"
.br
.RI "\fIalignment x change \fP"
.ti -1c
.RI "int \fBdax_isnull\fP"
.br
.ti -1c
.RI "double \fBday\fP"
.br
.RI "\fIalignment y change \fP"
.ti -1c
.RI "int \fBday_isnull\fP"
.br
.ti -1c
.RI "double \fBdaz\fP"
.br
.RI "\fIalignment z change \fP"
.ti -1c
.RI "int \fBdaz_isnull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Storage for getcenter query Used for the md2 ROTATE command that generates the centering movies\&. 
.PP
Definition at line 181 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t lspg_getcenter_struct::cond"

.PP
provides signaling for when the query is done 
.PP
Definition at line 183 of file pgpmac\&.h\&.
.SS "double lspg_getcenter_struct::dax"

.PP
alignment x change 
.PP
Definition at line 196 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::dax_isnull"

.PP
Definition at line 197 of file pgpmac\&.h\&.
.SS "double lspg_getcenter_struct::day"

.PP
alignment y change 
.PP
Definition at line 199 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::day_isnull"

.PP
Definition at line 200 of file pgpmac\&.h\&.
.SS "double lspg_getcenter_struct::daz"

.PP
alignment z change 
.PP
Definition at line 202 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::daz_isnull"

.PP
Definition at line 203 of file pgpmac\&.h\&.
.SS "double lspg_getcenter_struct::dcx"

.PP
center x change 
.PP
Definition at line 190 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::dcx_isnull"

.PP
Definition at line 191 of file pgpmac\&.h\&.
.SS "double lspg_getcenter_struct::dcy"

.PP
center y change 
.PP
Definition at line 193 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::dcy_isnull"

.PP
Definition at line 194 of file pgpmac\&.h\&.
.SS "pthread_mutex_t lspg_getcenter_struct::mutex"

.PP
don't let the threads collide! 
.PP
Definition at line 182 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::new_value_ready"

.PP
used with condition 
.PP
Definition at line 184 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::no_rows_returned"

.PP
flag in case no centering information was forthcoming 
.PP
Definition at line 185 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::zoom"

.PP
the next zoom level to go to before taking the next movie 
.PP
Definition at line 187 of file pgpmac\&.h\&.
.SS "int lspg_getcenter_struct::zoom_isnull"

.PP
Definition at line 188 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
