.TH "lspg_lock_diffractometer_struct" 3 "Sun Dec 16 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_lock_diffractometer_struct \- 
.PP
Object used to impliment locking the diffractometer Critical to exposure timing\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object used to impliment locking the diffractometer Critical to exposure timing\&. 
.PP
Definition at line 635 of file lspg\&.c\&.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t lspg_lock_diffractometer_struct::cond"

.PP
Definition at line 637 of file lspg\&.c\&.
.SS "pthread_mutex_t lspg_lock_diffractometer_struct::mutex"

.PP
Definition at line 636 of file lspg\&.c\&.
.SS "int lspg_lock_diffractometer_struct::new_value_ready"

.PP
Definition at line 638 of file lspg\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
