.TH "lspgQueryQueueStruct" 3 "13 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspgQueryQueueStruct \- 
.PP
Store each query along with it's callback function.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBqs\fP [LS_PG_QUERY_STRING_LENGTH]"
.br
.RI "\fIour queries should all be pretty short as we'll just be calling functions: fixed length here simplifies memory management \fP"
.ti -1c
.RI "void(* \fBonResponse\fP )(struct \fBlspgQueryQueueStruct\fP *qq, PGresult *pgr)"
.br
.RI "\fICallback function for when a query returns a result. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Store each query along with it's callback function. 

All calls are asynchronous 
.PP
Definition at line 51 of file lspg.c.
.SH "Field Documentation"
.PP 
.SS "void(* \fBlspgQueryQueueStruct::onResponse\fP)(struct \fBlspgQueryQueueStruct\fP *qq, PGresult *pgr)"
.PP
Callback function for when a query returns a result. 
.SS "char \fBlspgQueryQueueStruct::qs\fP[LS_PG_QUERY_STRING_LENGTH]"
.PP
our queries should all be pretty short as we'll just be calling functions: fixed length here simplifies memory management 
.PP
Definition at line 52 of file lspg.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
