.TH "lspg_nextshot_struct" 3 "Tue Jan 15 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspg_nextshot_struct \- 
.PP
Storage definition for nextshot query\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "\fIOur mutex for sanity in the multi-threaded program\&. \fP"
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.RI "\fICondition to wait for a response from our postgresql server\&. \fP"
.ti -1c
.RI "int \fBnew_value_ready\fP"
.br
.RI "\fIOur flag for the condition to wait for\&. \fP"
.ti -1c
.RI "int \fBno_rows_returned\fP"
.br
.RI "\fIflag indicating that no rows were returned\&. \fP"
.ti -1c
.RI "char * \fBdsdir\fP"
.br
.RI "\fIDirectory for data relative to the ESAF home directory\&. \fP"
.ti -1c
.RI "int \fBdsdir_isnull\fP"
.br
.ti -1c
.RI "char * \fBdspid\fP"
.br
.RI "\fIID string identifying this dataset\&. \fP"
.ti -1c
.RI "int \fBdspid_isnull\fP"
.br
.ti -1c
.RI "double \fBdsowidth\fP"
.br
.RI "\fIdataset defined oscillation width \fP"
.ti -1c
.RI "int \fBdsowidth_isnull\fP"
.br
.ti -1c
.RI "char * \fBdsoscaxis\fP"
.br
.RI "\fIdataset defined oscillation axis (always omega) \fP"
.ti -1c
.RI "int \fBdsoscaxis_isnull\fP"
.br
.ti -1c
.RI "double \fBdsexp\fP"
.br
.RI "\fIdataset defined exposure time \fP"
.ti -1c
.RI "int \fBdsexp_isnull\fP"
.br
.ti -1c
.RI "long long \fBskey\fP"
.br
.RI "\fIkey identifying a particulary image \fP"
.ti -1c
.RI "int \fBskey_isnull\fP"
.br
.ti -1c
.RI "double \fBsstart\fP"
.br
.RI "\fIstarting angle \fP"
.ti -1c
.RI "int \fBsstart_isnull\fP"
.br
.ti -1c
.RI "char * \fBsfn\fP"
.br
.RI "\fIfile name \fP"
.ti -1c
.RI "int \fBsfn_isnull\fP"
.br
.ti -1c
.RI "double \fBdsphi\fP"
.br
.RI "\fIdataset defined starting phi angle \fP"
.ti -1c
.RI "int \fBdsphi_isnull\fP"
.br
.ti -1c
.RI "double \fBdsomega\fP"
.br
.RI "\fIdataset defined starting omega angle \fP"
.ti -1c
.RI "int \fBdsomega_isnull\fP"
.br
.ti -1c
.RI "double \fBdskappa\fP"
.br
.RI "\fIdataset defined starting kappa angle \fP"
.ti -1c
.RI "int \fBdskappa_isnull\fP"
.br
.ti -1c
.RI "double \fBdsdist\fP"
.br
.RI "\fIdataset defined detector distance \fP"
.ti -1c
.RI "int \fBdsdist_isnull\fP"
.br
.ti -1c
.RI "double \fBdsnrg\fP"
.br
.RI "\fIdataset defined energy \fP"
.ti -1c
.RI "int \fBdsnrg_isnull\fP"
.br
.ti -1c
.RI "unsigned int \fBdshpid\fP"
.br
.RI "\fIsample holder ID \fP"
.ti -1c
.RI "int \fBdshpid_isnull\fP"
.br
.ti -1c
.RI "double \fBcx\fP"
.br
.RI "\fIcentering table x position \fP"
.ti -1c
.RI "int \fBcx_isnull\fP"
.br
.ti -1c
.RI "double \fBcy\fP"
.br
.RI "\fIcentering table y position \fP"
.ti -1c
.RI "int \fBcy_isnull\fP"
.br
.ti -1c
.RI "double \fBax\fP"
.br
.RI "\fIalignment table x position \fP"
.ti -1c
.RI "int \fBax_isnull\fP"
.br
.ti -1c
.RI "double \fBay\fP"
.br
.RI "\fIalignment table y position \fP"
.ti -1c
.RI "int \fBay_isnull\fP"
.br
.ti -1c
.RI "double \fBaz\fP"
.br
.RI "\fIalignment table z position \fP"
.ti -1c
.RI "int \fBaz_isnull\fP"
.br
.ti -1c
.RI "int \fBactive\fP"
.br
.RI "\fIflag: 1=move to indicated center position, 0=don't move center or alignment tables \fP"
.ti -1c
.RI "int \fBactive_isnull\fP"
.br
.ti -1c
.RI "int \fBsindex\fP"
.br
.RI "\fIindex of frame (used to generate the file extension) \fP"
.ti -1c
.RI "int \fBsindex_isnull\fP"
.br
.ti -1c
.RI "char * \fBstype\fP"
.br
.RI "\fI'Normal' or 'Gridsearch' \fP"
.ti -1c
.RI "int \fBstype_isnull\fP"
.br
.ti -1c
.RI "double \fBdsowidth2\fP"
.br
.RI "\fInext image oscillation width \fP"
.ti -1c
.RI "int \fBdsowidth2_isnull\fP"
.br
.ti -1c
.RI "char * \fBdsoscaxis2\fP"
.br
.RI "\fInext image ascillation axis (always 'omega') \fP"
.ti -1c
.RI "int \fBdsoscaxis2_isnull\fP"
.br
.ti -1c
.RI "double \fBdsexp2\fP"
.br
.RI "\fInext image exposure time \fP"
.ti -1c
.RI "int \fBdsexp2_isnull\fP"
.br
.ti -1c
.RI "double \fBsstart2\fP"
.br
.RI "\fInext image start angle \fP"
.ti -1c
.RI "int \fBsstart2_isnull\fP"
.br
.ti -1c
.RI "double \fBdsphi2\fP"
.br
.RI "\fInext image phi position \fP"
.ti -1c
.RI "int \fBdsphi2_isnull\fP"
.br
.ti -1c
.RI "double \fBdsomega2\fP"
.br
.RI "\fInext image omega position \fP"
.ti -1c
.RI "int \fBdsomega2_isnull\fP"
.br
.ti -1c
.RI "double \fBdskappa2\fP"
.br
.RI "\fInext image kappa position \fP"
.ti -1c
.RI "int \fBdskappa2_isnull\fP"
.br
.ti -1c
.RI "double \fBdsdist2\fP"
.br
.RI "\fInext image distance \fP"
.ti -1c
.RI "int \fBdsdist2_isnull\fP"
.br
.ti -1c
.RI "double \fBdsnrg2\fP"
.br
.RI "\fInext image energy \fP"
.ti -1c
.RI "int \fBdsnrg2_isnull\fP"
.br
.ti -1c
.RI "double \fBcx2\fP"
.br
.RI "\fInext image centering table x position \fP"
.ti -1c
.RI "int \fBcx2_isnull\fP"
.br
.ti -1c
.RI "double \fBcy2\fP"
.br
.RI "\fInext image centering table y position \fP"
.ti -1c
.RI "int \fBcy2_isnull\fP"
.br
.ti -1c
.RI "double \fBax2\fP"
.br
.RI "\fInext image alignment x position \fP"
.ti -1c
.RI "int \fBax2_isnull\fP"
.br
.ti -1c
.RI "double \fBay2\fP"
.br
.RI "\fInext image alignment y position \fP"
.ti -1c
.RI "int \fBay2_isnull\fP"
.br
.ti -1c
.RI "double \fBaz2\fP"
.br
.RI "\fInext image alignment z position \fP"
.ti -1c
.RI "int \fBaz2_isnull\fP"
.br
.ti -1c
.RI "int \fBactive2\fP"
.br
.RI "\fIflag: 1 if next image should use the above centering parameters \fP"
.ti -1c
.RI "int \fBactive2_isnull\fP"
.br
.ti -1c
.RI "int \fBsindex2\fP"
.br
.RI "\fInext image index number \fP"
.ti -1c
.RI "int \fBsindex2_isnull\fP"
.br
.ti -1c
.RI "char * \fBstype2\fP"
.br
.RI "\fInext image type ('Normal' or 'Gridsearch') \fP"
.ti -1c
.RI "int \fBstype2_isnull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Storage definition for nextshot query\&. 

The next shot query returns all the information needed to collect the next data frame\&. Since SQL allows for null fields independently from blank strings a separate integer is used as a flag for this case\&. This adds to the program complexity but allows for some important cases\&. Suck it up\&. 
.PP
Definition at line 271 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int lspg_nextshot_struct::active"

.PP
flag: 1=move to indicated center position, 0=don't move center or alignment tables 
.PP
Definition at line 334 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::active2"

.PP
flag: 1 if next image should use the above centering parameters 
.PP
Definition at line 385 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::active2_isnull"

.PP
Definition at line 386 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::active_isnull"

.PP
Definition at line 335 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::ax"

.PP
alignment table x position 
.PP
Definition at line 325 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::ax2"

.PP
next image alignment x position 
.PP
Definition at line 376 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::ax2_isnull"

.PP
Definition at line 377 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::ax_isnull"

.PP
Definition at line 326 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::ay"

.PP
alignment table y position 
.PP
Definition at line 328 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::ay2"

.PP
next image alignment y position 
.PP
Definition at line 379 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::ay2_isnull"

.PP
Definition at line 380 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::ay_isnull"

.PP
Definition at line 329 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::az"

.PP
alignment table z position 
.PP
Definition at line 331 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::az2"

.PP
next image alignment z position 
.PP
Definition at line 382 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::az2_isnull"

.PP
Definition at line 383 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::az_isnull"

.PP
Definition at line 332 of file pgpmac\&.h\&.
.SS "pthread_cond_t lspg_nextshot_struct::cond"

.PP
Condition to wait for a response from our postgresql server\&. 
.PP
Definition at line 273 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::cx"

.PP
centering table x position 
.PP
Definition at line 319 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::cx2"

.PP
next image centering table x position 
.PP
Definition at line 370 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::cx2_isnull"

.PP
Definition at line 371 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::cx_isnull"

.PP
Definition at line 320 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::cy"

.PP
centering table y position 
.PP
Definition at line 322 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::cy2"

.PP
next image centering table y position 
.PP
Definition at line 373 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::cy2_isnull"

.PP
Definition at line 374 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::cy_isnull"

.PP
Definition at line 323 of file pgpmac\&.h\&.
.SS "char* lspg_nextshot_struct::dsdir"

.PP
Directory for data relative to the ESAF home directory\&. 
.PP
Definition at line 277 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsdir_isnull"

.PP
Definition at line 278 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsdist"

.PP
dataset defined detector distance 
.PP
Definition at line 310 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsdist2"

.PP
next image distance 
.PP
Definition at line 364 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsdist2_isnull"

.PP
Definition at line 365 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsdist_isnull"

.PP
Definition at line 311 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsexp"

.PP
dataset defined exposure time 
.PP
Definition at line 289 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsexp2"

.PP
next image exposure time 
.PP
Definition at line 349 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsexp2_isnull"

.PP
Definition at line 350 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsexp_isnull"

.PP
Definition at line 290 of file pgpmac\&.h\&.
.SS "unsigned int lspg_nextshot_struct::dshpid"

.PP
sample holder ID 
.PP
Definition at line 316 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dshpid_isnull"

.PP
Definition at line 317 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dskappa"

.PP
dataset defined starting kappa angle 
.PP
Definition at line 307 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dskappa2"

.PP
next image kappa position 
.PP
Definition at line 361 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dskappa2_isnull"

.PP
Definition at line 362 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dskappa_isnull"

.PP
Definition at line 308 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsnrg"

.PP
dataset defined energy 
.PP
Definition at line 313 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsnrg2"

.PP
next image energy 
.PP
Definition at line 367 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsnrg2_isnull"

.PP
Definition at line 368 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsnrg_isnull"

.PP
Definition at line 314 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsomega"

.PP
dataset defined starting omega angle 
.PP
Definition at line 304 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsomega2"

.PP
next image omega position 
.PP
Definition at line 358 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsomega2_isnull"

.PP
Definition at line 359 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsomega_isnull"

.PP
Definition at line 305 of file pgpmac\&.h\&.
.SS "char* lspg_nextshot_struct::dsoscaxis"

.PP
dataset defined oscillation axis (always omega) 
.PP
Definition at line 286 of file pgpmac\&.h\&.
.SS "char* lspg_nextshot_struct::dsoscaxis2"

.PP
next image ascillation axis (always 'omega') 
.PP
Definition at line 346 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsoscaxis2_isnull"

.PP
Definition at line 347 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsoscaxis_isnull"

.PP
Definition at line 287 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsowidth"

.PP
dataset defined oscillation width 
.PP
Definition at line 283 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsowidth2"

.PP
next image oscillation width 
.PP
Definition at line 343 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsowidth2_isnull"

.PP
Definition at line 344 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsowidth_isnull"

.PP
Definition at line 284 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsphi"

.PP
dataset defined starting phi angle 
.PP
Definition at line 301 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::dsphi2"

.PP
next image phi position 
.PP
Definition at line 355 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsphi2_isnull"

.PP
Definition at line 356 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dsphi_isnull"

.PP
Definition at line 302 of file pgpmac\&.h\&.
.SS "char* lspg_nextshot_struct::dspid"

.PP
ID string identifying this dataset\&. 
.PP
Definition at line 280 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::dspid_isnull"

.PP
Definition at line 281 of file pgpmac\&.h\&.
.SS "pthread_mutex_t lspg_nextshot_struct::mutex"

.PP
Our mutex for sanity in the multi-threaded program\&. 
.PP
Definition at line 272 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::new_value_ready"

.PP
Our flag for the condition to wait for\&. 
.PP
Definition at line 274 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::no_rows_returned"

.PP
flag indicating that no rows were returned\&. 
.PP
Definition at line 275 of file pgpmac\&.h\&.
.SS "char* lspg_nextshot_struct::sfn"

.PP
file name 
.PP
Definition at line 298 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::sfn_isnull"

.PP
Definition at line 299 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::sindex"

.PP
index of frame (used to generate the file extension) 
.PP
Definition at line 337 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::sindex2"

.PP
next image index number 
.PP
Definition at line 388 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::sindex2_isnull"

.PP
Definition at line 389 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::sindex_isnull"

.PP
Definition at line 338 of file pgpmac\&.h\&.
.SS "long long lspg_nextshot_struct::skey"

.PP
key identifying a particulary image 
.PP
Definition at line 292 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::skey_isnull"

.PP
Definition at line 293 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::sstart"

.PP
starting angle 
.PP
Definition at line 295 of file pgpmac\&.h\&.
.SS "double lspg_nextshot_struct::sstart2"

.PP
next image start angle 
.PP
Definition at line 352 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::sstart2_isnull"

.PP
Definition at line 353 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::sstart_isnull"

.PP
Definition at line 296 of file pgpmac\&.h\&.
.SS "char* lspg_nextshot_struct::stype"

.PP
'Normal' or 'Gridsearch' 
.PP
Definition at line 340 of file pgpmac\&.h\&.
.SS "char* lspg_nextshot_struct::stype2"

.PP
next image type ('Normal' or 'Gridsearch') 
.PP
Definition at line 391 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::stype2_isnull"

.PP
Definition at line 392 of file pgpmac\&.h\&.
.SS "int lspg_nextshot_struct::stype_isnull"

.PP
Definition at line 341 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
