.TH "lspmac_dpascii_queue_struct" 3 "Thu Feb 14 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspmac_dpascii_queue_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBevent\fP"
.br
.ti -1c
.RI "char \fBpl\fP [160]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 368 of file lspmac\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char* lspmac_dpascii_queue_struct::event"

.PP
Definition at line 369 of file lspmac\&.c\&.
.SS "char lspmac_dpascii_queue_struct::pl[160]"

.PP
Definition at line 370 of file lspmac\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
