.TH "lspmac_cmd_queue_struct" 3 "Wed Nov 14 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspmac_cmd_queue_struct \- 
.PP
PMAC command queue item\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpmac_cmd_t\fP \fBpcmd\fP"
.br
.RI "\fIthe pmac command to send \fP"
.ti -1c
.RI "int \fBno_reply\fP"
.br
.RI "\fI1 = no reply is expected, 0 = expect a reply \fP"
.ti -1c
.RI "struct timespec \fBtime_sent\fP"
.br
.RI "\fItime this item was dequeued and sent to the pmac \fP"
.ti -1c
.RI "unsigned char \fBrbuff\fP [1400]"
.br
.RI "\fIbuffer for the returned bytes \fP"
.ti -1c
.RI "void(* \fBonResponse\fP )(struct \fBlspmac_cmd_queue_struct\fP *, int, unsigned char *)"
.br
.RI "\fIfunction to call when response is received\&. args are (int fd, nreturned, buffer) \fP"
.in -1c
.SH "Detailed Description"
.PP 
PMAC command queue item\&. 

Command queue items are fixed length to simplify memory management\&. 
.PP
Definition at line 58 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int lspmac_cmd_queue_struct::no_reply"

.PP
1 = no reply is expected, 0 = expect a reply 
.PP
Definition at line 60 of file pgpmac\&.h\&.
.SS "void(* lspmac_cmd_queue_struct::onResponse)(struct \fBlspmac_cmd_queue_struct\fP *, int, unsigned char *)"

.PP
function to call when response is received\&. args are (int fd, nreturned, buffer) 
.PP
Definition at line 63 of file pgpmac\&.h\&.
.SS "\fBpmac_cmd_t\fP lspmac_cmd_queue_struct::pcmd"

.PP
the pmac command to send 
.PP
Definition at line 59 of file pgpmac\&.h\&.
.SS "unsigned char lspmac_cmd_queue_struct::rbuff[1400]"

.PP
buffer for the returned bytes 
.PP
Definition at line 62 of file pgpmac\&.h\&.
.SS "struct timespec lspmac_cmd_queue_struct::time_sent"

.PP
time this item was dequeued and sent to the pmac 
.PP
Definition at line 61 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
