.TH "lspmac_bi_struct" 3 "Thu Feb 14 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspmac_bi_struct \- 
.PP
Storage for binary inputs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int * \fBptr\fP"
.br
.RI "\fIpoints to the location in the status buffer \fP"
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "\fIso we don't get confused \fP"
.ti -1c
.RI "int \fBmask\fP"
.br
.RI "\fImask for the bit in the status register \fP"
.ti -1c
.RI "int \fBposition\fP"
.br
.RI "\fIthe current value\&. \fP"
.ti -1c
.RI "int \fBprevious\fP"
.br
.RI "\fIthe previous value \fP"
.ti -1c
.RI "int \fBfirst_time\fP"
.br
.RI "\fIflag indicating we've not read the input even once \fP"
.ti -1c
.RI "char * \fBchangeEventOn\fP"
.br
.RI "\fIEvent to send when the value changes to 1\&. \fP"
.ti -1c
.RI "char * \fBchangeEventOff\fP"
.br
.RI "\fIEvent to send when the value changes to 0\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Storage for binary inputs\&. 
.PP
Definition at line 160 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* lspmac_bi_struct::changeEventOff"

.PP
Event to send when the value changes to 0\&. 
.PP
Definition at line 168 of file pgpmac\&.h\&.
.SS "char* lspmac_bi_struct::changeEventOn"

.PP
Event to send when the value changes to 1\&. 
.PP
Definition at line 167 of file pgpmac\&.h\&.
.SS "int lspmac_bi_struct::first_time"

.PP
flag indicating we've not read the input even once 
.PP
Definition at line 166 of file pgpmac\&.h\&.
.SS "int lspmac_bi_struct::mask"

.PP
mask for the bit in the status register 
.PP
Definition at line 163 of file pgpmac\&.h\&.
.SS "pthread_mutex_t lspmac_bi_struct::mutex"

.PP
so we don't get confused 
.PP
Definition at line 162 of file pgpmac\&.h\&.
.SS "int lspmac_bi_struct::position"

.PP
the current value\&. 
.PP
Definition at line 164 of file pgpmac\&.h\&.
.SS "int lspmac_bi_struct::previous"

.PP
the previous value 
.PP
Definition at line 165 of file pgpmac\&.h\&.
.SS "int* lspmac_bi_struct::ptr"

.PP
points to the location in the status buffer 
.PP
Definition at line 161 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
