.TH "lspmac_motor_struct" 3 "Fri Dec 14 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspmac_motor_struct \- 
.PP
Motor information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "\fIcoordinate waiting for motor to be done \fP"
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.RI "\fIused to signal when a motor is done moving \fP"
.ti -1c
.RI "int \fBnot_done\fP"
.br
.RI "\fIset to 1 when request is queued, zero after motion has toggled \fP"
.ti -1c
.RI "int \fBlspg_initialized\fP"
.br
.RI "\fIbit flags: bit 0 = motor initialized by database, bit 1 = px\&.kvs value initialized \fP"
.ti -1c
.RI "\fBlskvs_kvs_list_t\fP * \fBpresets\fP"
.br
.RI "\fIlist of preset positions \fP"
.ti -1c
.RI "regex_t \fBpreset_regex\fP"
.br
.RI "\fIbuffer used by regex routines to find preset positions for this motor \fP"
.ti -1c
.RI "void(* \fBread\fP )(struct \fBlspmac_motor_struct\fP *)"
.br
.RI "\fImethod to read the motor status and position \fP"
.ti -1c
.RI "int \fBmotion_seen\fP"
.br
.RI "\fIset to 1 when motion has been verified to have started \fP"
.ti -1c
.RI "struct \fBlspmac_cmd_queue_struct\fP * \fBpq\fP"
.br
.RI "\fIthe queue item requesting motion\&. Used to check time request was made \fP"
.ti -1c
.RI "char ** \fBhome\fP"
.br
.RI "\fIpmac commands to home motor \fP"
.ti -1c
.RI "int \fBhoming\fP"
.br
.RI "\fIHoming routine started\&. \fP"
.ti -1c
.RI "int \fBrequested_pos_cnts\fP"
.br
.RI "\fIrequested position \fP"
.ti -1c
.RI "int * \fBactual_pos_cnts_p\fP"
.br
.RI "\fIpointer to the md2_status structure to the actual position \fP"
.ti -1c
.RI "int \fBactual_pos_cnts\fP"
.br
.RI "\fIlocal copy of actual counts so only our mutex is needed to read \fP"
.ti -1c
.RI "double \fBposition\fP"
.br
.RI "\fIscaled position \fP"
.ti -1c
.RI "double \fBreported_position\fP"
.br
.RI "\fIprevious position reported to the database \fP"
.ti -1c
.RI "double \fBrequested_position\fP"
.br
.RI "\fIThe position as requested by the user\&. \fP"
.ti -1c
.RI "double \fBupdate_resolution\fP"
.br
.RI "\fIChange needs to be at least this big to report as a new position to the database\&. \fP"
.ti -1c
.RI "char * \fBupdate_format\fP"
.br
.RI "\fIspecial format string to create text array for px\&.kvs update (lsupdate) \fP"
.ti -1c
.RI "int * \fBstatus1_p\fP"
.br
.RI "\fIFirst 24 bit PMAC motor status word\&. \fP"
.ti -1c
.RI "int \fBstatus1\fP"
.br
.RI "\fIlocal copy of status1 \fP"
.ti -1c
.RI "int * \fBstatus2_p\fP"
.br
.RI "\fISectond 24 bit PMAC motor status word\&. \fP"
.ti -1c
.RI "int \fBstatus2\fP"
.br
.RI "\fIlocal copy of status2 \fP"
.ti -1c
.RI "char \fBstatuss\fP [64]"
.br
.RI "\fIshort text summarizing status \fP"
.ti -1c
.RI "int \fBmotor_num\fP"
.br
.RI "\fIpmac motor number \fP"
.ti -1c
.RI "int \fBcoord_num\fP"
.br
.RI "\fIcoordinate system this motor belongs to (0 if none) \fP"
.ti -1c
.RI "char * \fBaxis\fP"
.br
.RI "\fIthe axis (X, Y, Z, etc) or null if not in a coordinate system \fP"
.ti -1c
.RI "char * \fBdac_mvar\fP"
.br
.RI "\fIcontrolling mvariable as a string \fP"
.ti -1c
.RI "char * \fBname\fP"
.br
.RI "\fIName of motor as refered by ls database kvs table\&. \fP"
.ti -1c
.RI "char * \fBunits\fP"
.br
.RI "\fIstring to use as the units \fP"
.ti -1c
.RI "char * \fBformat\fP"
.br
.RI "\fIprintf format \fP"
.ti -1c
.RI "char * \fBwrite_fmt\fP"
.br
.RI "\fIFormat string to write requested position to PMAC used for binary io\&. \fP"
.ti -1c
.RI "int * \fBread_ptr\fP"
.br
.RI "\fIWith read_mask finds bit to read for binary i/o\&. \fP"
.ti -1c
.RI "int \fBread_mask\fP"
.br
.RI "\fIWIth read_ptr find bit to read for binary i/o\&. \fP"
.ti -1c
.RI "void(* \fBmoveAbs\fP )(struct \fBlspmac_motor_struct\fP *, double)"
.br
.RI "\fIfunction to move the motor \fP"
.ti -1c
.RI "\fBlsredis_obj_t\fP * \fBu2c\fP"
.br
.RI "\fIconversion from counts to units: 0\&.0 means not loaded yet \fP"
.ti -1c
.RI "double * \fBlut\fP"
.br
.RI "\fIlookup table (instead of u2c) \fP"
.ti -1c
.RI "int \fBnlut\fP"
.br
.RI "\fIlength of lut \fP"
.ti -1c
.RI "double \fBmax_speed\fP"
.br
.RI "\fIour maximum speed (cts/msec) \fP"
.ti -1c
.RI "double \fBmax_accel\fP"
.br
.RI "\fIour maximum acceleration (cts/msec^2) \fP"
.ti -1c
.RI "WINDOW * \fBwin\fP"
.br
.RI "\fIour ncurses window \fP"
.in -1c
.SH "Detailed Description"
.PP 
Motor information\&. 

A catchall for motors and motor like objects\&. Not all members are used by all objects\&. 
.PP
Definition at line 116 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int lspmac_motor_struct::actual_pos_cnts"

.PP
local copy of actual counts so only our mutex is needed to read 
.PP
Definition at line 131 of file pgpmac\&.h\&.
.SS "int* lspmac_motor_struct::actual_pos_cnts_p"

.PP
pointer to the md2_status structure to the actual position 
.PP
Definition at line 130 of file pgpmac\&.h\&.
.SS "char* lspmac_motor_struct::axis"

.PP
the axis (X, Y, Z, etc) or null if not in a coordinate system 
.PP
Definition at line 144 of file pgpmac\&.h\&.
.SS "pthread_cond_t lspmac_motor_struct::cond"

.PP
used to signal when a motor is done moving 
.PP
Definition at line 118 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::coord_num"

.PP
coordinate system this motor belongs to (0 if none) 
.PP
Definition at line 143 of file pgpmac\&.h\&.
.SS "char* lspmac_motor_struct::dac_mvar"

.PP
controlling mvariable as a string 
.PP
Definition at line 145 of file pgpmac\&.h\&.
.SS "char* lspmac_motor_struct::format"

.PP
printf format 
.PP
Definition at line 148 of file pgpmac\&.h\&.
.SS "char** lspmac_motor_struct::home"

.PP
pmac commands to home motor 
.PP
Definition at line 127 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::homing"

.PP
Homing routine started\&. 
.PP
Definition at line 128 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::lspg_initialized"

.PP
bit flags: bit 0 = motor initialized by database, bit 1 = px\&.kvs value initialized 
.PP
Definition at line 120 of file pgpmac\&.h\&.
.SS "double* lspmac_motor_struct::lut"

.PP
lookup table (instead of u2c) 
.PP
Definition at line 154 of file pgpmac\&.h\&.
.SS "double lspmac_motor_struct::max_accel"

.PP
our maximum acceleration (cts/msec^2) 
.PP
Definition at line 157 of file pgpmac\&.h\&.
.SS "double lspmac_motor_struct::max_speed"

.PP
our maximum speed (cts/msec) 
.PP
Definition at line 156 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::motion_seen"

.PP
set to 1 when motion has been verified to have started 
.PP
Definition at line 124 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::motor_num"

.PP
pmac motor number 
.PP
Definition at line 142 of file pgpmac\&.h\&.
.SS "void(* lspmac_motor_struct::moveAbs)(struct \fBlspmac_motor_struct\fP *, double)"

.PP
function to move the motor 
.PP
Definition at line 152 of file pgpmac\&.h\&.
.SS "pthread_mutex_t lspmac_motor_struct::mutex"

.PP
coordinate waiting for motor to be done 
.PP
Definition at line 117 of file pgpmac\&.h\&.
.SS "char* lspmac_motor_struct::name"

.PP
Name of motor as refered by ls database kvs table\&. 
.PP
Definition at line 146 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::nlut"

.PP
length of lut 
.PP
Definition at line 155 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::not_done"

.PP
set to 1 when request is queued, zero after motion has toggled 
.PP
Definition at line 119 of file pgpmac\&.h\&.
.SS "double lspmac_motor_struct::position"

.PP
scaled position 
.PP
Definition at line 132 of file pgpmac\&.h\&.
.SS "struct \fBlspmac_cmd_queue_struct\fP* lspmac_motor_struct::pq"

.PP
the queue item requesting motion\&. Used to check time request was made 
.PP
Definition at line 125 of file pgpmac\&.h\&.
.SS "regex_t lspmac_motor_struct::preset_regex"

.PP
buffer used by regex routines to find preset positions for this motor 
.PP
Definition at line 122 of file pgpmac\&.h\&.
.SS "\fBlskvs_kvs_list_t\fP* lspmac_motor_struct::presets"

.PP
list of preset positions 
.PP
Definition at line 121 of file pgpmac\&.h\&.
.SS "void(* lspmac_motor_struct::read)(struct \fBlspmac_motor_struct\fP *)"

.PP
method to read the motor status and position 
.PP
Definition at line 123 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::read_mask"

.PP
WIth read_ptr find bit to read for binary i/o\&. 
.PP
Definition at line 151 of file pgpmac\&.h\&.
.SS "int* lspmac_motor_struct::read_ptr"

.PP
With read_mask finds bit to read for binary i/o\&. 
.PP
Definition at line 150 of file pgpmac\&.h\&.
.SS "double lspmac_motor_struct::reported_position"

.PP
previous position reported to the database 
.PP
Definition at line 133 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::requested_pos_cnts"

.PP
requested position 
.PP
Definition at line 129 of file pgpmac\&.h\&.
.SS "double lspmac_motor_struct::requested_position"

.PP
The position as requested by the user\&. 
.PP
Definition at line 134 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::status1"

.PP
local copy of status1 
.PP
Definition at line 138 of file pgpmac\&.h\&.
.SS "int* lspmac_motor_struct::status1_p"

.PP
First 24 bit PMAC motor status word\&. 
.PP
Definition at line 137 of file pgpmac\&.h\&.
.SS "int lspmac_motor_struct::status2"

.PP
local copy of status2 
.PP
Definition at line 140 of file pgpmac\&.h\&.
.SS "int* lspmac_motor_struct::status2_p"

.PP
Sectond 24 bit PMAC motor status word\&. 
.PP
Definition at line 139 of file pgpmac\&.h\&.
.SS "char lspmac_motor_struct::statuss[64]"

.PP
short text summarizing status 
.PP
Definition at line 141 of file pgpmac\&.h\&.
.SS "\fBlsredis_obj_t\fP* lspmac_motor_struct::u2c"

.PP
conversion from counts to units: 0\&.0 means not loaded yet 
.PP
Definition at line 153 of file pgpmac\&.h\&.
.SS "char* lspmac_motor_struct::units"

.PP
string to use as the units 
.PP
Definition at line 147 of file pgpmac\&.h\&.
.SS "char* lspmac_motor_struct::update_format"

.PP
special format string to create text array for px\&.kvs update (lsupdate) 
.PP
Definition at line 136 of file pgpmac\&.h\&.
.SS "double lspmac_motor_struct::update_resolution"

.PP
Change needs to be at least this big to report as a new position to the database\&. 
.PP
Definition at line 135 of file pgpmac\&.h\&.
.SS "WINDOW* lspmac_motor_struct::win"

.PP
our ncurses window 
.PP
Definition at line 158 of file pgpmac\&.h\&.
.SS "char* lspmac_motor_struct::write_fmt"

.PP
Format string to write requested position to PMAC used for binary io\&. 
.PP
Definition at line 149 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
