.TH "lspmac_ascii_buffers_struct" 3 "Tue Feb 12 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lspmac_ascii_buffers_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcommand_buf\fP"
.br
.ti -1c
.RI "uint16_t \fBcommand_buf_cc\fP"
.br
.ti -1c
.RI "char \fBcommand_str\fP [160]"
.br
.ti -1c
.RI "uint16_t \fBresponse_buf\fP"
.br
.ti -1c
.RI "uint16_t \fBresponse_n\fP"
.br
.ti -1c
.RI "char \fBresponse_str\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 354 of file lspmac\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t lspmac_ascii_buffers_struct::command_buf"

.PP
Definition at line 356 of file lspmac\&.c\&.
.SS "uint16_t lspmac_ascii_buffers_struct::command_buf_cc"

.PP
Definition at line 357 of file lspmac\&.c\&.
.SS "char lspmac_ascii_buffers_struct::command_str[160]"

.PP
Definition at line 358 of file lspmac\&.c\&.
.SS "uint16_t lspmac_ascii_buffers_struct::response_buf"

.PP
Definition at line 359 of file lspmac\&.c\&.
.SS "uint16_t lspmac_ascii_buffers_struct::response_n"

.PP
Definition at line 360 of file lspmac\&.c\&.
.SS "char lspmac_ascii_buffers_struct::response_str[256]"

.PP
Definition at line 361 of file lspmac\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
