.TH "lsredis_preset_list_struct" 3 "Wed May 22 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsredis_preset_list_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlsredis_preset_list_struct\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "\fBlsredis_obj_t\fP * \fBname\fP"
.br
.ti -1c
.RI "\fBlsredis_obj_t\fP * \fBposition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file lsredis\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int lsredis_preset_list_struct::index"

.PP
Definition at line 100 of file lsredis\&.c\&.
.SS "char* lsredis_preset_list_struct::key"

.PP
Definition at line 99 of file lsredis\&.c\&.
.SS "\fBlsredis_obj_t\fP* lsredis_preset_list_struct::name"

.PP
Definition at line 101 of file lsredis\&.c\&.
.SS "struct \fBlsredis_preset_list_struct\fP* lsredis_preset_list_struct::next"

.PP
Definition at line 98 of file lsredis\&.c\&.
.SS "\fBlsredis_obj_t\fP* lsredis_preset_list_struct::position"

.PP
Definition at line 102 of file lsredis\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
