.TH "lsredis_obj_struct" 3 "Fri May 23 2014" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsredis_obj_struct \- 
.PP
Redis Object Basic object whose value is sychronized with our redis db\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "\fIDon't let anyone use an old value\&. \fP"
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.RI "\fIwait for a valid value \fP"
.ti -1c
.RI "struct \fBlsredis_obj_struct\fP * \fBnext\fP"
.br
.RI "\fIthe next in our list (I guess this is going to be a linked list) \fP"
.ti -1c
.RI "char \fBcreating\fP"
.br
.RI "\fI1 if this key does not exist and we haven't set it yet: read will create and set an empty string value, write will create and set the requested value \fP"
.ti -1c
.RI "char \fBvalid\fP"
.br
.RI "\fI1 if we think the value is good, 0 otherwise \fP"
.ti -1c
.RI "int \fBwait_for_me\fP"
.br
.RI "\fINumber of times we need to see our publication before we start accepting new values\&. \fP"
.ti -1c
.RI "char * \fBkey\fP"
.br
.RI "\fIThe redis key for this object\&. \fP"
.ti -1c
.RI "char * \fBevents_name\fP"
.br
.RI "\fIName used to generate events (normally key without the station id) \fP"
.ti -1c
.RI "int \fBvalue_length\fP"
.br
.RI "\fINumber of bytes allocated for value (not value's string length) \fP"
.ti -1c
.RI "char * \fBvalue\fP"
.br
.RI "\fIour value \fP"
.ti -1c
.RI "double \fBdvalue\fP"
.br
.RI "\fIour value as a double \fP"
.ti -1c
.RI "long int \fBlvalue\fP"
.br
.RI "\fIour value as a long \fP"
.ti -1c
.RI "char ** \fBavalue\fP"
.br
.RI "\fIour value as an array of strings \fP"
.ti -1c
.RI "int \fBbvalue\fP"
.br
.RI "\fIour value as a boolean (1 or 0) -1 means we couldn't figure it out \fP"
.ti -1c
.RI "char \fBcvalue\fP"
.br
.RI "\fIjust the first character of our value \fP"
.ti -1c
.RI "int \fBhits\fP"
.br
.RI "\fInumber of times we've searched for this key \fP"
.in -1c
.SH "Detailed Description"
.PP 
Redis Object Basic object whose value is sychronized with our redis db\&. 
.PP
Definition at line 38 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char** lsredis_obj_struct::avalue"

.PP
our value as an array of strings 
.PP
Definition at line 51 of file pgpmac\&.h\&.
.SS "int lsredis_obj_struct::bvalue"

.PP
our value as a boolean (1 or 0) -1 means we couldn't figure it out 
.PP
Definition at line 52 of file pgpmac\&.h\&.
.SS "pthread_cond_t lsredis_obj_struct::cond"

.PP
wait for a valid value 
.PP
Definition at line 40 of file pgpmac\&.h\&.
.SS "char lsredis_obj_struct::creating"

.PP
1 if this key does not exist and we haven't set it yet: read will create and set an empty string value, write will create and set the requested value 
.PP
Definition at line 42 of file pgpmac\&.h\&.
.SS "char lsredis_obj_struct::cvalue"

.PP
just the first character of our value 
.PP
Definition at line 53 of file pgpmac\&.h\&.
.SS "double lsredis_obj_struct::dvalue"

.PP
our value as a double 
.PP
Definition at line 49 of file pgpmac\&.h\&.
.SS "char* lsredis_obj_struct::events_name"

.PP
Name used to generate events (normally key without the station id) 
.PP
Definition at line 46 of file pgpmac\&.h\&.
.SS "int lsredis_obj_struct::hits"

.PP
number of times we've searched for this key 
.PP
Definition at line 54 of file pgpmac\&.h\&.
.SS "char* lsredis_obj_struct::key"

.PP
The redis key for this object\&. 
.PP
Definition at line 45 of file pgpmac\&.h\&.
.SS "long int lsredis_obj_struct::lvalue"

.PP
our value as a long 
.PP
Definition at line 50 of file pgpmac\&.h\&.
.SS "pthread_mutex_t lsredis_obj_struct::mutex"

.PP
Don't let anyone use an old value\&. 
.PP
Definition at line 39 of file pgpmac\&.h\&.
.SS "struct \fBlsredis_obj_struct\fP* lsredis_obj_struct::next"

.PP
the next in our list (I guess this is going to be a linked list) 
.PP
Definition at line 41 of file pgpmac\&.h\&.
.SS "char lsredis_obj_struct::valid"

.PP
1 if we think the value is good, 0 otherwise 
.PP
Definition at line 43 of file pgpmac\&.h\&.
.SS "char* lsredis_obj_struct::value"

.PP
our value 
.PP
Definition at line 48 of file pgpmac\&.h\&.
.SS "int lsredis_obj_struct::value_length"

.PP
Number of bytes allocated for value (not value's string length) 
.PP
Definition at line 47 of file pgpmac\&.h\&.
.SS "int lsredis_obj_struct::wait_for_me"

.PP
Number of times we need to see our publication before we start accepting new values\&. 
.PP
Definition at line 44 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
