.TH "lstimer_list_struct" 3 "Tue Feb 12 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lstimer_list_struct \- 
.PP
Everything we need to know about a timer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBshots\fP"
.br
.RI "\fIrun this many times: -1 means reload forever, 0 means we are done with this timer and it may be reused \fP"
.ti -1c
.RI "unsigned long int \fBncalls\fP"
.br
.RI "\fItrack how many times we triggered a callback (like an unsigned long int is really needed) \fP"
.ti -1c
.RI "char \fBevent\fP [\fBLSEVENTS_EVENT_LENGTH\fP]"
.br
.RI "\fIthe event to send \fP"
.ti -1c
.RI "long int \fBnext_secs\fP"
.br
.RI "\fIepoch (seconds) of next alarm \fP"
.ti -1c
.RI "long int \fBnext_nsecs\fP"
.br
.RI "\fInano seconds of next alarm \fP"
.ti -1c
.RI "long int \fBdelay_secs\fP"
.br
.RI "\fInumber of seconds for a periodic delay \fP"
.ti -1c
.RI "long int \fBdelay_nsecs\fP"
.br
.RI "\fInano seconds of delay \fP"
.ti -1c
.RI "long int \fBlast_secs\fP"
.br
.RI "\fIthe last time this timer was triggered \fP"
.ti -1c
.RI "long int \fBlast_nsecs\fP"
.br
.RI "\fIthe last time this timer was triggered \fP"
.ti -1c
.RI "long int \fBinit_secs\fP"
.br
.RI "\fIour initialization time \fP"
.ti -1c
.RI "long int \fBinit_nsecs\fP"
.br
.RI "\fIour initialization time \fP"
.in -1c
.SH "Detailed Description"
.PP 
Everything we need to know about a timer\&. 
.PP
Definition at line 22 of file lstimer\&.c\&.
.SH "Field Documentation"
.PP 
.SS "long int lstimer_list_struct::delay_nsecs"

.PP
nano seconds of delay 
.PP
Definition at line 29 of file lstimer\&.c\&.
.SS "long int lstimer_list_struct::delay_secs"

.PP
number of seconds for a periodic delay 
.PP
Definition at line 28 of file lstimer\&.c\&.
.SS "char lstimer_list_struct::event[\fBLSEVENTS_EVENT_LENGTH\fP]"

.PP
the event to send 
.PP
Definition at line 25 of file lstimer\&.c\&.
.SS "long int lstimer_list_struct::init_nsecs"

.PP
our initialization time 
.PP
Definition at line 33 of file lstimer\&.c\&.
.SS "long int lstimer_list_struct::init_secs"

.PP
our initialization time 
.PP
Definition at line 32 of file lstimer\&.c\&.
.SS "long int lstimer_list_struct::last_nsecs"

.PP
the last time this timer was triggered 
.PP
Definition at line 31 of file lstimer\&.c\&.
.SS "long int lstimer_list_struct::last_secs"

.PP
the last time this timer was triggered 
.PP
Definition at line 30 of file lstimer\&.c\&.
.SS "unsigned long int lstimer_list_struct::ncalls"

.PP
track how many times we triggered a callback (like an unsigned long int is really needed) 
.PP
Definition at line 24 of file lstimer\&.c\&.
.SS "long int lstimer_list_struct::next_nsecs"

.PP
nano seconds of next alarm 
.PP
Definition at line 27 of file lstimer\&.c\&.
.SS "long int lstimer_list_struct::next_secs"

.PP
epoch (seconds) of next alarm 
.PP
Definition at line 26 of file lstimer\&.c\&.
.SS "int lstimer_list_struct::shots"

.PP
run this many times: -1 means reload forever, 0 means we are done with this timer and it may be reused 
.PP
Definition at line 23 of file lstimer\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
