.TH "md2StatusStruct" 3 "14 Nov 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md2StatusStruct \- 
.PP
The block of memory retrieved in a status request.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdummy1\fP"
.br
.ti -1c
.RI "int \fBomega_status_1\fP"
.br
.ti -1c
.RI "int \fBalignx_status_1\fP"
.br
.ti -1c
.RI "int \fBaligny_status_1\fP"
.br
.ti -1c
.RI "int \fBalignz_status_1\fP"
.br
.ti -1c
.RI "int \fBanalyzer_status_1\fP"
.br
.ti -1c
.RI "int \fBzoom_status_1\fP"
.br
.ti -1c
.RI "int \fBaperturey_status_1\fP"
.br
.ti -1c
.RI "int \fBaperturez_status_1\fP"
.br
.ti -1c
.RI "int \fBcapy_status_1\fP"
.br
.ti -1c
.RI "int \fBcapz_status_1\fP"
.br
.ti -1c
.RI "int \fBscint_status_1\fP"
.br
.ti -1c
.RI "int \fBcenterx_status_1\fP"
.br
.ti -1c
.RI "int \fBcentery_status_1\fP"
.br
.ti -1c
.RI "int \fBkappa_status_1\fP"
.br
.ti -1c
.RI "int \fBphi_status_1\fP"
.br
.ti -1c
.RI "int \fBdummy2\fP"
.br
.ti -1c
.RI "int \fBomega_status_2\fP"
.br
.ti -1c
.RI "int \fBalignx_status_2\fP"
.br
.ti -1c
.RI "int \fBaligny_status_2\fP"
.br
.ti -1c
.RI "int \fBalignz_status_2\fP"
.br
.ti -1c
.RI "int \fBanalyzer_status_2\fP"
.br
.ti -1c
.RI "int \fBzoom_status_2\fP"
.br
.ti -1c
.RI "int \fBaperturey_status_2\fP"
.br
.ti -1c
.RI "int \fBaperturez_status_2\fP"
.br
.ti -1c
.RI "int \fBcapy_status_2\fP"
.br
.ti -1c
.RI "int \fBcapz_status_2\fP"
.br
.ti -1c
.RI "int \fBscint_status_2\fP"
.br
.ti -1c
.RI "int \fBcenterx_status_2\fP"
.br
.ti -1c
.RI "int \fBcentery_status_2\fP"
.br
.ti -1c
.RI "int \fBkappa_status_2\fP"
.br
.ti -1c
.RI "int \fBphi_status_2\fP"
.br
.ti -1c
.RI "int \fBdummy3\fP"
.br
.ti -1c
.RI "int \fBomega_act_pos\fP"
.br
.ti -1c
.RI "int \fBalignx_act_pos\fP"
.br
.ti -1c
.RI "int \fBaligny_act_pos\fP"
.br
.ti -1c
.RI "int \fBalignz_act_pos\fP"
.br
.ti -1c
.RI "int \fBanalyzer_act_pos\fP"
.br
.ti -1c
.RI "int \fBzoom_act_pos\fP"
.br
.ti -1c
.RI "int \fBaperturey_act_pos\fP"
.br
.ti -1c
.RI "int \fBaperturez_act_pos\fP"
.br
.ti -1c
.RI "int \fBcapy_act_pos\fP"
.br
.ti -1c
.RI "int \fBcapz_act_pos\fP"
.br
.ti -1c
.RI "int \fBscint_act_pos\fP"
.br
.ti -1c
.RI "int \fBcenterx_act_pos\fP"
.br
.ti -1c
.RI "int \fBcentery_act_pos\fP"
.br
.ti -1c
.RI "int \fBkappa_act_pos\fP"
.br
.ti -1c
.RI "int \fBphi_act_pos\fP"
.br
.ti -1c
.RI "int \fBacc11c_1\fP"
.br
.ti -1c
.RI "int \fBacc11c_2\fP"
.br
.ti -1c
.RI "int \fBacc11c_3\fP"
.br
.ti -1c
.RI "int \fBacc11c_5\fP"
.br
.ti -1c
.RI "int \fBacc11c_6\fP"
.br
.ti -1c
.RI "int \fBfront_dac\fP"
.br
.ti -1c
.RI "int \fBback_dac\fP"
.br
.ti -1c
.RI "int \fBscint_piezo\fP"
.br
.ti -1c
.RI "int \fBdummy4\fP"
.br
.ti -1c
.RI "int \fBdummy5\fP"
.br
.ti -1c
.RI "int \fBdummy6\fP"
.br
.ti -1c
.RI "int \fBdummy7\fP"
.br
.ti -1c
.RI "int \fBdummy8\fP"
.br
.ti -1c
.RI "int \fBdummy9\fP"
.br
.ti -1c
.RI "int \fBdummyA\fP"
.br
.ti -1c
.RI "int \fBdummyB\fP"
.br
.ti -1c
.RI "int \fBfs_is_open\fP"
.br
.ti -1c
.RI "int \fBphiscan\fP"
.br
.ti -1c
.RI "int \fBfs_has_opened\fP"
.br
.ti -1c
.RI "int \fBfs_has_opened_globally\fP"
.br
.ti -1c
.RI "int \fBnumber_passes\fP"
.br
.ti -1c
.RI "int \fBmoving_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The block of memory retrieved in a status request. 
.PP
Definition at line 184 of file lspmac.c.
.SH "Field Documentation"
.PP 
.SS "int \fBmd2StatusStruct::acc11c_1\fP"
.PP
Definition at line 251 of file lspmac.c.
.SS "int \fBmd2StatusStruct::acc11c_2\fP"
.PP
Definition at line 252 of file lspmac.c.
.SS "int \fBmd2StatusStruct::acc11c_3\fP"
.PP
Definition at line 253 of file lspmac.c.
.SS "int \fBmd2StatusStruct::acc11c_5\fP"
.PP
Definition at line 254 of file lspmac.c.
.SS "int \fBmd2StatusStruct::acc11c_6\fP"
.PP
Definition at line 255 of file lspmac.c.
.SS "int \fBmd2StatusStruct::alignx_act_pos\fP"
.PP
Definition at line 235 of file lspmac.c.
.SS "int \fBmd2StatusStruct::alignx_status_1\fP"
.PP
Definition at line 201 of file lspmac.c.
.SS "int \fBmd2StatusStruct::alignx_status_2\fP"
.PP
Definition at line 218 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aligny_act_pos\fP"
.PP
Definition at line 236 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aligny_status_1\fP"
.PP
Definition at line 202 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aligny_status_2\fP"
.PP
Definition at line 219 of file lspmac.c.
.SS "int \fBmd2StatusStruct::alignz_act_pos\fP"
.PP
Definition at line 237 of file lspmac.c.
.SS "int \fBmd2StatusStruct::alignz_status_1\fP"
.PP
Definition at line 203 of file lspmac.c.
.SS "int \fBmd2StatusStruct::alignz_status_2\fP"
.PP
Definition at line 220 of file lspmac.c.
.SS "int \fBmd2StatusStruct::analyzer_act_pos\fP"
.PP
Definition at line 238 of file lspmac.c.
.SS "int \fBmd2StatusStruct::analyzer_status_1\fP"
.PP
Definition at line 204 of file lspmac.c.
.SS "int \fBmd2StatusStruct::analyzer_status_2\fP"
.PP
Definition at line 221 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aperturey_act_pos\fP"
.PP
Definition at line 240 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aperturey_status_1\fP"
.PP
Definition at line 206 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aperturey_status_2\fP"
.PP
Definition at line 223 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aperturez_act_pos\fP"
.PP
Definition at line 241 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aperturez_status_1\fP"
.PP
Definition at line 207 of file lspmac.c.
.SS "int \fBmd2StatusStruct::aperturez_status_2\fP"
.PP
Definition at line 224 of file lspmac.c.
.SS "int \fBmd2StatusStruct::back_dac\fP"
.PP
Definition at line 257 of file lspmac.c.
.SS "int \fBmd2StatusStruct::capy_act_pos\fP"
.PP
Definition at line 242 of file lspmac.c.
.SS "int \fBmd2StatusStruct::capy_status_1\fP"
.PP
Definition at line 208 of file lspmac.c.
.SS "int \fBmd2StatusStruct::capy_status_2\fP"
.PP
Definition at line 225 of file lspmac.c.
.SS "int \fBmd2StatusStruct::capz_act_pos\fP"
.PP
Definition at line 243 of file lspmac.c.
.SS "int \fBmd2StatusStruct::capz_status_1\fP"
.PP
Definition at line 209 of file lspmac.c.
.SS "int \fBmd2StatusStruct::capz_status_2\fP"
.PP
Definition at line 226 of file lspmac.c.
.SS "int \fBmd2StatusStruct::centerx_act_pos\fP"
.PP
Definition at line 245 of file lspmac.c.
.SS "int \fBmd2StatusStruct::centerx_status_1\fP"
.PP
Definition at line 211 of file lspmac.c.
.SS "int \fBmd2StatusStruct::centerx_status_2\fP"
.PP
Definition at line 228 of file lspmac.c.
.SS "int \fBmd2StatusStruct::centery_act_pos\fP"
.PP
Definition at line 246 of file lspmac.c.
.SS "int \fBmd2StatusStruct::centery_status_1\fP"
.PP
Definition at line 212 of file lspmac.c.
.SS "int \fBmd2StatusStruct::centery_status_2\fP"
.PP
Definition at line 229 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy1\fP"
.PP
Definition at line 199 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy2\fP"
.PP
Definition at line 216 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy3\fP"
.PP
Definition at line 233 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy4\fP"
.PP
Definition at line 260 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy5\fP"
.PP
Definition at line 261 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy6\fP"
.PP
Definition at line 262 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy7\fP"
.PP
Definition at line 263 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy8\fP"
.PP
Definition at line 264 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummy9\fP"
.PP
Definition at line 265 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummyA\fP"
.PP
Definition at line 266 of file lspmac.c.
.SS "int \fBmd2StatusStruct::dummyB\fP"
.PP
Definition at line 267 of file lspmac.c.
.SS "int \fBmd2StatusStruct::front_dac\fP"
.PP
Definition at line 256 of file lspmac.c.
.SS "int \fBmd2StatusStruct::fs_has_opened\fP"
.PP
Definition at line 271 of file lspmac.c.
.SS "int \fBmd2StatusStruct::fs_has_opened_globally\fP"
.PP
Definition at line 272 of file lspmac.c.
.SS "int \fBmd2StatusStruct::fs_is_open\fP"
.PP
Definition at line 269 of file lspmac.c.
.SS "int \fBmd2StatusStruct::kappa_act_pos\fP"
.PP
Definition at line 247 of file lspmac.c.
.SS "int \fBmd2StatusStruct::kappa_status_1\fP"
.PP
Definition at line 213 of file lspmac.c.
.SS "int \fBmd2StatusStruct::kappa_status_2\fP"
.PP
Definition at line 230 of file lspmac.c.
.SS "int \fBmd2StatusStruct::moving_flags\fP"
.PP
Definition at line 275 of file lspmac.c.
.SS "int \fBmd2StatusStruct::number_passes\fP"
.PP
Definition at line 273 of file lspmac.c.
.SS "int \fBmd2StatusStruct::omega_act_pos\fP"
.PP
Definition at line 234 of file lspmac.c.
.SS "int \fBmd2StatusStruct::omega_status_1\fP"
.PP
Definition at line 200 of file lspmac.c.
.SS "int \fBmd2StatusStruct::omega_status_2\fP"
.PP
Definition at line 217 of file lspmac.c.
.SS "int \fBmd2StatusStruct::phi_act_pos\fP"
.PP
Definition at line 248 of file lspmac.c.
.SS "int \fBmd2StatusStruct::phi_status_1\fP"
.PP
Definition at line 214 of file lspmac.c.
.SS "int \fBmd2StatusStruct::phi_status_2\fP"
.PP
Definition at line 231 of file lspmac.c.
.SS "int \fBmd2StatusStruct::phiscan\fP"
.PP
Definition at line 270 of file lspmac.c.
.SS "int \fBmd2StatusStruct::scint_act_pos\fP"
.PP
Definition at line 244 of file lspmac.c.
.SS "int \fBmd2StatusStruct::scint_piezo\fP"
.PP
Definition at line 258 of file lspmac.c.
.SS "int \fBmd2StatusStruct::scint_status_1\fP"
.PP
Definition at line 210 of file lspmac.c.
.SS "int \fBmd2StatusStruct::scint_status_2\fP"
.PP
Definition at line 227 of file lspmac.c.
.SS "int \fBmd2StatusStruct::zoom_act_pos\fP"
.PP
Definition at line 239 of file lspmac.c.
.SS "int \fBmd2StatusStruct::zoom_status_1\fP"
.PP
Definition at line 205 of file lspmac.c.
.SS "int \fBmd2StatusStruct::zoom_status_2\fP"
.PP
Definition at line 222 of file lspmac.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code.
