.TH "md2StatusStruct" 3 "Tue Jan 29 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md2StatusStruct \- 
.PP
The block of memory retrieved in a status request\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdummy1\fP"
.br
.ti -1c
.RI "int \fBomega_status_1\fP"
.br
.ti -1c
.RI "int \fBalignx_status_1\fP"
.br
.ti -1c
.RI "int \fBaligny_status_1\fP"
.br
.ti -1c
.RI "int \fBalignz_status_1\fP"
.br
.ti -1c
.RI "int \fBanalyzer_status_1\fP"
.br
.ti -1c
.RI "int \fBzoom_status_1\fP"
.br
.ti -1c
.RI "int \fBaperturey_status_1\fP"
.br
.ti -1c
.RI "int \fBaperturez_status_1\fP"
.br
.ti -1c
.RI "int \fBcapy_status_1\fP"
.br
.ti -1c
.RI "int \fBcapz_status_1\fP"
.br
.ti -1c
.RI "int \fBscint_status_1\fP"
.br
.ti -1c
.RI "int \fBcenterx_status_1\fP"
.br
.ti -1c
.RI "int \fBcentery_status_1\fP"
.br
.ti -1c
.RI "int \fBkappa_status_1\fP"
.br
.ti -1c
.RI "int \fBphi_status_1\fP"
.br
.ti -1c
.RI "int \fBdummy2\fP"
.br
.ti -1c
.RI "int \fBomega_status_2\fP"
.br
.ti -1c
.RI "int \fBalignx_status_2\fP"
.br
.ti -1c
.RI "int \fBaligny_status_2\fP"
.br
.ti -1c
.RI "int \fBalignz_status_2\fP"
.br
.ti -1c
.RI "int \fBanalyzer_status_2\fP"
.br
.ti -1c
.RI "int \fBzoom_status_2\fP"
.br
.ti -1c
.RI "int \fBaperturey_status_2\fP"
.br
.ti -1c
.RI "int \fBaperturez_status_2\fP"
.br
.ti -1c
.RI "int \fBcapy_status_2\fP"
.br
.ti -1c
.RI "int \fBcapz_status_2\fP"
.br
.ti -1c
.RI "int \fBscint_status_2\fP"
.br
.ti -1c
.RI "int \fBcenterx_status_2\fP"
.br
.ti -1c
.RI "int \fBcentery_status_2\fP"
.br
.ti -1c
.RI "int \fBkappa_status_2\fP"
.br
.ti -1c
.RI "int \fBphi_status_2\fP"
.br
.ti -1c
.RI "int \fBdummy3\fP"
.br
.ti -1c
.RI "int \fBomega_act_pos\fP"
.br
.ti -1c
.RI "int \fBalignx_act_pos\fP"
.br
.ti -1c
.RI "int \fBaligny_act_pos\fP"
.br
.ti -1c
.RI "int \fBalignz_act_pos\fP"
.br
.ti -1c
.RI "int \fBanalyzer_act_pos\fP"
.br
.ti -1c
.RI "int \fBzoom_act_pos\fP"
.br
.ti -1c
.RI "int \fBaperturey_act_pos\fP"
.br
.ti -1c
.RI "int \fBaperturez_act_pos\fP"
.br
.ti -1c
.RI "int \fBcapy_act_pos\fP"
.br
.ti -1c
.RI "int \fBcapz_act_pos\fP"
.br
.ti -1c
.RI "int \fBscint_act_pos\fP"
.br
.ti -1c
.RI "int \fBcenterx_act_pos\fP"
.br
.ti -1c
.RI "int \fBcentery_act_pos\fP"
.br
.ti -1c
.RI "int \fBkappa_act_pos\fP"
.br
.ti -1c
.RI "int \fBphi_act_pos\fP"
.br
.ti -1c
.RI "int \fBacc11c_1\fP"
.br
.ti -1c
.RI "int \fBacc11c_2\fP"
.br
.ti -1c
.RI "int \fBacc11c_3\fP"
.br
.ti -1c
.RI "int \fBacc11c_5\fP"
.br
.ti -1c
.RI "int \fBacc11c_6\fP"
.br
.ti -1c
.RI "int \fBfront_dac\fP"
.br
.ti -1c
.RI "int \fBback_dac\fP"
.br
.ti -1c
.RI "int \fBscint_piezo\fP"
.br
.ti -1c
.RI "int \fBdummy4\fP"
.br
.ti -1c
.RI "int \fBdummy5\fP"
.br
.ti -1c
.RI "int \fBdummy6\fP"
.br
.ti -1c
.RI "int \fBdummy7\fP"
.br
.ti -1c
.RI "int \fBdummy8\fP"
.br
.ti -1c
.RI "int \fBdummy9\fP"
.br
.ti -1c
.RI "int \fBdummyA\fP"
.br
.ti -1c
.RI "int \fBdummyB\fP"
.br
.ti -1c
.RI "int \fBfs_is_open\fP"
.br
.ti -1c
.RI "int \fBphiscan\fP"
.br
.ti -1c
.RI "int \fBfs_has_opened\fP"
.br
.ti -1c
.RI "int \fBfs_has_opened_globally\fP"
.br
.ti -1c
.RI "int \fBnumber_passes\fP"
.br
.ti -1c
.RI "int \fBmoving_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The block of memory retrieved in a status request\&. 
.PP
Definition at line 245 of file lspmac\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int md2StatusStruct::acc11c_1"

.PP
Definition at line 312 of file lspmac\&.c\&.
.SS "int md2StatusStruct::acc11c_2"

.PP
Definition at line 313 of file lspmac\&.c\&.
.SS "int md2StatusStruct::acc11c_3"

.PP
Definition at line 314 of file lspmac\&.c\&.
.SS "int md2StatusStruct::acc11c_5"

.PP
Definition at line 315 of file lspmac\&.c\&.
.SS "int md2StatusStruct::acc11c_6"

.PP
Definition at line 316 of file lspmac\&.c\&.
.SS "int md2StatusStruct::alignx_act_pos"

.PP
Definition at line 296 of file lspmac\&.c\&.
.SS "int md2StatusStruct::alignx_status_1"

.PP
Definition at line 262 of file lspmac\&.c\&.
.SS "int md2StatusStruct::alignx_status_2"

.PP
Definition at line 279 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aligny_act_pos"

.PP
Definition at line 297 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aligny_status_1"

.PP
Definition at line 263 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aligny_status_2"

.PP
Definition at line 280 of file lspmac\&.c\&.
.SS "int md2StatusStruct::alignz_act_pos"

.PP
Definition at line 298 of file lspmac\&.c\&.
.SS "int md2StatusStruct::alignz_status_1"

.PP
Definition at line 264 of file lspmac\&.c\&.
.SS "int md2StatusStruct::alignz_status_2"

.PP
Definition at line 281 of file lspmac\&.c\&.
.SS "int md2StatusStruct::analyzer_act_pos"

.PP
Definition at line 299 of file lspmac\&.c\&.
.SS "int md2StatusStruct::analyzer_status_1"

.PP
Definition at line 265 of file lspmac\&.c\&.
.SS "int md2StatusStruct::analyzer_status_2"

.PP
Definition at line 282 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aperturey_act_pos"

.PP
Definition at line 301 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aperturey_status_1"

.PP
Definition at line 267 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aperturey_status_2"

.PP
Definition at line 284 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aperturez_act_pos"

.PP
Definition at line 302 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aperturez_status_1"

.PP
Definition at line 268 of file lspmac\&.c\&.
.SS "int md2StatusStruct::aperturez_status_2"

.PP
Definition at line 285 of file lspmac\&.c\&.
.SS "int md2StatusStruct::back_dac"

.PP
Definition at line 318 of file lspmac\&.c\&.
.SS "int md2StatusStruct::capy_act_pos"

.PP
Definition at line 303 of file lspmac\&.c\&.
.SS "int md2StatusStruct::capy_status_1"

.PP
Definition at line 269 of file lspmac\&.c\&.
.SS "int md2StatusStruct::capy_status_2"

.PP
Definition at line 286 of file lspmac\&.c\&.
.SS "int md2StatusStruct::capz_act_pos"

.PP
Definition at line 304 of file lspmac\&.c\&.
.SS "int md2StatusStruct::capz_status_1"

.PP
Definition at line 270 of file lspmac\&.c\&.
.SS "int md2StatusStruct::capz_status_2"

.PP
Definition at line 287 of file lspmac\&.c\&.
.SS "int md2StatusStruct::centerx_act_pos"

.PP
Definition at line 306 of file lspmac\&.c\&.
.SS "int md2StatusStruct::centerx_status_1"

.PP
Definition at line 272 of file lspmac\&.c\&.
.SS "int md2StatusStruct::centerx_status_2"

.PP
Definition at line 289 of file lspmac\&.c\&.
.SS "int md2StatusStruct::centery_act_pos"

.PP
Definition at line 307 of file lspmac\&.c\&.
.SS "int md2StatusStruct::centery_status_1"

.PP
Definition at line 273 of file lspmac\&.c\&.
.SS "int md2StatusStruct::centery_status_2"

.PP
Definition at line 290 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy1"

.PP
Definition at line 260 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy2"

.PP
Definition at line 277 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy3"

.PP
Definition at line 294 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy4"

.PP
Definition at line 321 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy5"

.PP
Definition at line 322 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy6"

.PP
Definition at line 323 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy7"

.PP
Definition at line 324 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy8"

.PP
Definition at line 325 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummy9"

.PP
Definition at line 326 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummyA"

.PP
Definition at line 327 of file lspmac\&.c\&.
.SS "int md2StatusStruct::dummyB"

.PP
Definition at line 328 of file lspmac\&.c\&.
.SS "int md2StatusStruct::front_dac"

.PP
Definition at line 317 of file lspmac\&.c\&.
.SS "int md2StatusStruct::fs_has_opened"

.PP
Definition at line 332 of file lspmac\&.c\&.
.SS "int md2StatusStruct::fs_has_opened_globally"

.PP
Definition at line 333 of file lspmac\&.c\&.
.SS "int md2StatusStruct::fs_is_open"

.PP
Definition at line 330 of file lspmac\&.c\&.
.SS "int md2StatusStruct::kappa_act_pos"

.PP
Definition at line 308 of file lspmac\&.c\&.
.SS "int md2StatusStruct::kappa_status_1"

.PP
Definition at line 274 of file lspmac\&.c\&.
.SS "int md2StatusStruct::kappa_status_2"

.PP
Definition at line 291 of file lspmac\&.c\&.
.SS "int md2StatusStruct::moving_flags"

.PP
Definition at line 336 of file lspmac\&.c\&.
.SS "int md2StatusStruct::number_passes"

.PP
Definition at line 334 of file lspmac\&.c\&.
.SS "int md2StatusStruct::omega_act_pos"

.PP
Definition at line 295 of file lspmac\&.c\&.
.SS "int md2StatusStruct::omega_status_1"

.PP
Definition at line 261 of file lspmac\&.c\&.
.SS "int md2StatusStruct::omega_status_2"

.PP
Definition at line 278 of file lspmac\&.c\&.
.SS "int md2StatusStruct::phi_act_pos"

.PP
Definition at line 309 of file lspmac\&.c\&.
.SS "int md2StatusStruct::phi_status_1"

.PP
Definition at line 275 of file lspmac\&.c\&.
.SS "int md2StatusStruct::phi_status_2"

.PP
Definition at line 292 of file lspmac\&.c\&.
.SS "int md2StatusStruct::phiscan"

.PP
Definition at line 331 of file lspmac\&.c\&.
.SS "int md2StatusStruct::scint_act_pos"

.PP
Definition at line 305 of file lspmac\&.c\&.
.SS "int md2StatusStruct::scint_piezo"

.PP
Definition at line 319 of file lspmac\&.c\&.
.SS "int md2StatusStruct::scint_status_1"

.PP
Definition at line 271 of file lspmac\&.c\&.
.SS "int md2StatusStruct::scint_status_2"

.PP
Definition at line 288 of file lspmac\&.c\&.
.SS "int md2StatusStruct::zoom_act_pos"

.PP
Definition at line 300 of file lspmac\&.c\&.
.SS "int md2StatusStruct::zoom_status_1"

.PP
Definition at line 266 of file lspmac\&.c\&.
.SS "int md2StatusStruct::zoom_status_2"

.PP
Definition at line 283 of file lspmac\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
