.TH "mk_pgpmac_redis" 3 "Mon Dec 24 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mk_pgpmac_redis \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBhead\fP 'stns\&.2'"
.br
.ti -1c
.RI "dictionary \fBmotor_dict\fP"
.br
.ti -1c
.RI "list \fBmotor_field_lists\fP"
.br
.ti -1c
.RI "list \fBbi_list\fP ['CryoSwitch']"
.br
.ti -1c
.RI "dictionary \fBmotor_presets\fP"
.br
.ti -1c
.RI "list \fBzoom_settings\fP"
.br
.ti -1c
.RI "list \fBv\fP \fBmotor_dict\fP[m]"
.br
.ti -1c
.RI "int \fBi\fP 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list mk_pgpmac_redis\&.bi_list ['CryoSwitch']"

.PP
Definition at line 177 of file mk_pgpmac_redis\&.py\&.
.SS "string mk_pgpmac_redis\&.head 'stns\&.2'"

.PP
Definition at line 4 of file mk_pgpmac_redis\&.py\&.
.SS "int mk_pgpmac_redis\&.i 0"

.PP
Definition at line 260 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.motor_dict"

.PP
Definition at line 6 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.motor_field_lists"

.PP
Definition at line 142 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.motor_presets"

.PP
Definition at line 179 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.v \fBmotor_dict\fP[m]"

.PP
Definition at line 253 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.zoom_settings"
\fBInitial value:\fP
.PP
.nf
1 [
2     #lev   front  back  pos     scalex  scaley
3     [1,     4\&.0,   8\&.0,  34100, 2\&.7083,  3\&.3442],
4     [2,     6\&.0,   8\&.1,  31440, 2\&.2487,  2\&.2776],
5     [3,     6\&.5,   8\&.2,  27460, 1\&.7520,  1\&.7550],
6     [4,     7\&.0,   8\&.3,  23480, 1\&.3360,  1\&.3400],
7     [5,     8\&.0,  10\&.0,  19500, 1\&.0140,  1\&.0110],
8     [6,     9\&.0,  12\&.0,  15520, 0\&.7710,  0\&.7760],
9     [7,    10\&.0,  17\&.0,  11540, 0\&.5880,  0\&.5920],
10     [8,    12\&.0,  25\&.0,   7560, 0\&.4460,  0\&.4480],
11     [9,    15\&.0,  37\&.0,   3580, 0\&.3410,  0\&.3460],
12     [10,   16\&.0,  42\&.0,      0, 0\&.2700,  0\&.2690]
13     ]
.fi
.PP
Definition at line 227 of file mk_pgpmac_redis\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
