.TH "mk_pgpmac_redis" 3 "Sun Feb 17 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mk_pgpmac_redis \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmk_home\fP"
.br
.ti -1c
.RI "def \fBmk_active_init\fP"
.br
.ti -1c
.RI "def \fBmk_inactive_init\fP"
.br
.ti -1c
.RI "def \fBactive_simulation\fP"
.br
.ti -1c
.RI "def \fBasis\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBhead\fP sys\&.argv[1]"
.br
.ti -1c
.RI "list \fBpref_ini\fP sys\&.argv[2]"
.br
.ti -1c
.RI "list \fBhard_ini\fP sys\&.argv[3]"
.br
.ti -1c
.RI "dictionary \fBconfigs\fP"
.br
.ti -1c
.RI "dictionary \fBmotor_dict\fP"
.br
.ti -1c
.RI "dictionary \fBhard_ini_fields\fP"
.br
.ti -1c
.RI "list \fBmotor_field_lists\fP"
.br
.ti -1c
.RI "list \fBbi_list\fP ['CryoSwitch']"
.br
.ti -1c
.RI "dictionary \fBmotor_presets\fP"
.br
.ti -1c
.RI "list \fBzoom_settings\fP"
.br
.ti -1c
.RI "tuple \fBhi\fP \fBiniParser\&.iniParser\fP( \fBhard_ini\fP)"
.br
.ti -1c
.RI "list \fBv\fP \fBmotor_dict\fP[m]"
.br
.ti -1c
.RI "string \fBf\fP 'HSETNX'"
.br
.ti -1c
.RI "list \fBxlate\fP \fBhard_ini_fields\fP[k]"
.br
.ti -1c
.RI "tuple \fBpi\fP \fBiniParser\&.iniParser\fP( \fBpref_ini\fP)"
.br
.ti -1c
.RI "int \fBi\fP 0"
.br
.ti -1c
.RI "tuple \fBppos\fP pi\&.get( section, option)"
.br
.ti -1c
.RI "string \fBfnc\fP 'HSETNX'"
.br
.ti -1c
.RI "tuple \fBb\fP pi\&.get( section, 'LightIntensity')"
.br
.ti -1c
.RI "tuple \fBp\fP pi\&.get( section, 'MotorPosition')"
.br
.ti -1c
.RI "tuple \fBx\fP pi\&.get( section, 'ScaleX')"
.br
.ti -1c
.RI "tuple \fBy\fP pi\&.get( section, 'ScaleY')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def mk_pgpmac_redis\&.active_simulation (sim)"

.PP
Definition at line 231 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
231 
232 def active_simulation( sim):
233     if str(sim) != '0':
234         rtn = '0'
235     else:
236         rtn = '1'
237     return rtn

.fi
.SS "def mk_pgpmac_redis\&.asis (arg)"

.PP
Definition at line 238 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
238 
239 def asis( arg):
240     return arg

.fi
.SS "def mk_pgpmac_redis\&.mk_active_init (d)"

.PP
Definition at line 209 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
209 
210 def mk_active_init( d):
211     if not d\&.has_key('motor_num') or not d\&.has_key('coord_num') or not d\&.has_key( 'axis'):
212         return ''
213     motor_num = int(d['motor_num'])
214     coord_num = int(d['coord_num'])
215     axis      = str(d['axis'])
216     mask      = 1 << (motor_num - 1)
217     if motor_num < 1 or motor_num > 32:
218         return ''
219     return '{M%d=1,&%d#%d->%s,'M700=(M700 | $%0x) ^ $%0x'}' % (motor_num + 30, coord_num, motor_num, axis, mask, mask)

.fi
.SS "def mk_pgpmac_redis\&.mk_home (mname, d)"

.PP
Definition at line 194 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
194 
195 def mk_home( mname, d):
196     if not d\&.has_key('motor_num') or not d\&.has_key('coord_num'):
197         return ''
198     motor_num = int(d['motor_num'])
199     coord_num = int(d['coord_num'])
200     if motor_num < 1 or motor_num > 32:
201         return ''
202     
203     if mname == 'kappa':
204         prog_num = 119
205     else:
206         prog_num = motor_num
207 
208     return '{#%d$,M%d=1,&%dE,#%d&%dB%dR}' % (motor_num, motor_num+400, coord_num, motor_num, coord_num, prog_num)

.fi
.SS "def mk_pgpmac_redis\&.mk_inactive_init (d)"

.PP
Definition at line 220 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
220 
221 def mk_inactive_init( d):
222     if not d\&.has_key('motor_num') or not d\&.has_key('coord_num') or not d\&.has_key( 'axis'):
223         return ''
224     motor_num = int(d['motor_num'])
225     coord_num = int(d['coord_num'])
226     axis      = str(d['axis'])
227     mask      = 1 << (motor_num - 1)
228     if motor_num < 1 or motor_num > 32:
229         return ''
230     return '{M%d=0,&%d#%d->0,'M700=M700 | $%0x'}' % (motor_num + 30, coord_num, motor_num, mask)

.fi
.SH "Variable Documentation"
.PP 
.SS "tuple mk_pgpmac_redis\&.b pi\&.get( section, 'LightIntensity')"

.PP
Definition at line 496 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.bi_list ['CryoSwitch']"

.PP
Definition at line 302 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.configs"
\fBInitial value:\fP
.PP
.nf
1 {
2     'orange-2'            : { 're' : 'redis\\&.kvseq|stns\\&.2\\&.(\&.+)', 'head' : 'stns\&.2', 'pub' : 'MD2-21-ID-E'},
3     'orange-2\&.ls-cat\&.org' : { 're' : 'redis\\&.kvseq|stns\\&.2\\&.(\&.+)', 'head' : 'stns\&.2', 'pub' : 'MD2-21-ID-E'},
4     'venison\&.ls-cat\&.org'  : { 're' : 'redis\\&.kvseq|stns\\&.2\\&.(\&.+)', 'head' : 'stns\&.2', 'pub' : 'MD2-21-ID-E'}
5 }
.fi
.PP
Definition at line 26 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.f 'HSETNX'"

.PP
Definition at line 437 of file mk_pgpmac_redis\&.py\&.
.SS "string mk_pgpmac_redis\&.fnc 'HSETNX'"

.PP
Definition at line 487 of file mk_pgpmac_redis\&.py\&.
.SS "mk_pgpmac_redis\&.hard_ini sys\&.argv[3]"

.PP
Definition at line 21 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.hard_ini_fields"
\fBInitial value:\fP
.PP
.nf
1 {
2     'active'          : ['Simulation', active_simulation],
3     'coord_num'       : ['CoordinateSystem', asis],
4     'largeStep'       : ['LargeStep', asis],
5     'maxPosition'     : ['MaxPosition', asis],
6     'minPosition'     : ['MinPosition', asis],
7     'motor_num'       : ['MotorNumber', asis],
8     'neutralPosition' : ['NeutralPosition', asis],
9     'precision'       : ['Precision', asis],
10     'smallStep'       : ['SmallStep', asis],
11     'u2c'             : ['UnitRatio', asis]
12     }
.fi
.PP
Definition at line 241 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.head sys\&.argv[1]"

.PP
Definition at line 13 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.hi \fBiniParser\&.iniParser\fP( \fBhard_ini\fP)"

.PP
Definition at line 393 of file mk_pgpmac_redis\&.py\&.
.SS "int mk_pgpmac_redis\&.i 0"

.PP
Definition at line 461 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.motor_dict"

.PP
Definition at line 64 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.motor_field_lists"

.PP
Definition at line 263 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.motor_presets"

.PP
Definition at line 304 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.p pi\&.get( section, 'MotorPosition')"

.PP
Definition at line 503 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.pi \fBiniParser\&.iniParser\fP( \fBpref_ini\fP)"

.PP
Definition at line 458 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.ppos pi\&.get( section, option)"

.PP
Definition at line 469 of file mk_pgpmac_redis\&.py\&.
.SS "mk_pgpmac_redis\&.pref_ini sys\&.argv[2]"

.PP
Definition at line 16 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.v \fBmotor_dict\fP[m]"

.PP
Definition at line 436 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.x pi\&.get( section, 'ScaleX')"

.PP
Definition at line 510 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.xlate \fBhard_ini_fields\fP[k]"

.PP
Definition at line 441 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.y pi\&.get( section, 'ScaleY')"

.PP
Definition at line 517 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.zoom_settings"
\fBInitial value:\fP
.PP
.nf
1 [
2     #lev   front  back  pos     scalex  scaley   section
3     [1,     4\&.0,   8\&.0,  34100, 2\&.7083,  3\&.3442, 'CoaxCam\&.Zoom1'],
4     [2,     6\&.0,   8\&.1,  31440, 2\&.2487,  2\&.2776, 'CoaxCam\&.Zoom2'],
5     [3,     6\&.5,   8\&.2,  27460, 1\&.7520,  1\&.7550, 'CoaxCam\&.Zoom3'],
6     [4,     7\&.0,   8\&.3,  23480, 1\&.3360,  1\&.3400, 'CoaxCam\&.Zoom4'],
7     [5,     8\&.0,  10\&.0,  19500, 1\&.0140,  1\&.0110, 'CoaxCam\&.Zoom5'],
8     [6,     9\&.0,  12\&.0,  15520, 0\&.7710,  0\&.7760, 'CoaxCam\&.Zoom6'],
9     [7,    10\&.0,  17\&.0,  11540, 0\&.5880,  0\&.5920, 'CoaxCam\&.Zoom7'],
10     [8,    12\&.0,  25\&.0,   7560, 0\&.4460,  0\&.4480, 'CoaxCam\&.Zoom8'],
11     [9,    15\&.0,  37\&.0,   3580, 0\&.3410,  0\&.3460, 'CoaxCam\&.Zoom9'],
12     [10,   16\&.0,  42\&.0,      0, 0\&.2700,  0\&.2690, 'CoaxCam\&.Zoom10']
13     ]
.fi
.PP
Definition at line 371 of file mk_pgpmac_redis\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
