.TH "mk_pgpmac_redis" 3 "Wed May 22 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mk_pgpmac_redis \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmk_home\fP"
.br
.ti -1c
.RI "def \fBmk_active_init\fP"
.br
.ti -1c
.RI "def \fBmk_inactive_init\fP"
.br
.ti -1c
.RI "def \fBactive_simulation\fP"
.br
.ti -1c
.RI "def \fBasis\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBhead\fP sys\&.argv[1]"
.br
.ti -1c
.RI "list \fBpref_ini\fP sys\&.argv[2]"
.br
.ti -1c
.RI "list \fBhard_ini\fP sys\&.argv[3]"
.br
.ti -1c
.RI "dictionary \fBconfigs\fP"
.br
.ti -1c
.RI "dictionary \fBplcc2_dict\fP"
.br
.ti -1c
.RI "dictionary \fBmotor_dict\fP"
.br
.ti -1c
.RI "dictionary \fBhard_ini_fields\fP"
.br
.ti -1c
.RI "list \fBmotor_field_lists\fP"
.br
.ti -1c
.RI "list \fBbi_list\fP ['CryoSwitch']"
.br
.ti -1c
.RI "dictionary \fBmotor_presets\fP"
.br
.ti -1c
.RI "list \fBzoom_settings\fP"
.br
.ti -1c
.RI "tuple \fBhi\fP \fBiniParser\&.iniParser\fP( \fBhard_ini\fP)"
.br
.ti -1c
.RI "list \fBv\fP \fBmotor_dict\fP[m]"
.br
.ti -1c
.RI "string \fBf\fP 'HSETNX'"
.br
.ti -1c
.RI "list \fBxlate\fP \fBhard_ini_fields\fP[k]"
.br
.ti -1c
.RI "tuple \fBpi\fP \fBiniParser\&.iniParser\fP( \fBpref_ini\fP)"
.br
.ti -1c
.RI "int \fBi\fP 0"
.br
.ti -1c
.RI "tuple \fBppos\fP pi\&.get( section, option)"
.br
.ti -1c
.RI "string \fBfnc\fP 'HSETNX'"
.br
.ti -1c
.RI "tuple \fBb\fP pi\&.get( section, 'LightIntensity')"
.br
.ti -1c
.RI "tuple \fBp\fP pi\&.get( section, 'MotorPosition')"
.br
.ti -1c
.RI "tuple \fBx\fP pi\&.get( section, 'ScaleX')"
.br
.ti -1c
.RI "tuple \fBy\fP pi\&.get( section, 'ScaleY')"
.br
.ti -1c
.RI "tuple \fBplcc2_file\fP open( '%s-plcc2\&.pmc' % (head), 'w')"
.br
.ti -1c
.RI "tuple \fBmotor_num\fP int( \fBmotor_dict\fP[m]['motor_num'])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def mk_pgpmac_redis\&.active_simulation (sim)"

.PP
Definition at line 424 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
424 
425 def active_simulation( sim):
426     if str(sim) != '0':
427         rtn = '0'
428     else:
429         rtn = '1'
430     return rtn

.fi
.SS "def mk_pgpmac_redis\&.asis (arg)"

.PP
Definition at line 431 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
431 
432 def asis( arg):
433     return arg

.fi
.SS "def mk_pgpmac_redis\&.mk_active_init (d)"

.PP
Definition at line 402 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
402 
403 def mk_active_init( d):
404     if not d\&.has_key('motor_num') or not d\&.has_key('coord_num') or not d\&.has_key( 'axis'):
405         return ''
406     motor_num = int(d['motor_num'])
407     coord_num = int(d['coord_num'])
408     axis      = str(d['axis'])
409     mask      = 1 << (motor_num - 1)
410     if motor_num < 1 or motor_num > 32:
411         return ''
412     return '{M%d=1,&%d#%d->%s,'M700=(M700 | $%0x) ^ $%0x'}' % (motor_num + 30, coord_num, motor_num, axis, mask, mask)

.fi
.SS "def mk_pgpmac_redis\&.mk_home (mname, d)"

.PP
Definition at line 387 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
387 
388 def mk_home( mname, d):
389     if not d\&.has_key('motor_num') or not d\&.has_key('coord_num'):
390         return ''
391     motor_num = int(d['motor_num'])
392     coord_num = int(d['coord_num'])
393     if motor_num < 1 or motor_num > 32:
394         return ''
395     
396     if mname == 'kappa':
397         prog_num = 119
398     else:
399         prog_num = motor_num
400 
401     return '{#%d$,M%d=1,&%dE,#%d&%dB%dR}' % (motor_num, motor_num+400, coord_num, motor_num, coord_num, prog_num)

.fi
.SS "def mk_pgpmac_redis\&.mk_inactive_init (d)"

.PP
Definition at line 413 of file mk_pgpmac_redis\&.py\&.
.PP
.nf
413 
414 def mk_inactive_init( d):
415     if not d\&.has_key('motor_num') or not d\&.has_key('coord_num') or not d\&.has_key( 'axis'):
416         return ''
417     motor_num = int(d['motor_num'])
418     coord_num = int(d['coord_num'])
419     axis      = str(d['axis'])
420     mask      = 1 << (motor_num - 1)
421     if motor_num < 1 or motor_num > 32:
422         return ''
423     return '{M%d=0,&%d#%d->0,'M700=M700 | $%0x'}' % (motor_num + 30, coord_num, motor_num, mask)

.fi
.SH "Variable Documentation"
.PP 
.SS "tuple mk_pgpmac_redis\&.b pi\&.get( section, 'LightIntensity')"

.PP
Definition at line 702 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.bi_list ['CryoSwitch']"

.PP
Definition at line 495 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.configs"
\fBInitial value:\fP
.PP
.nf
1 {
2     'orange-2'            : { 're' : 'redis\\&.kvseq|stns\\&.2\\&.(\&.+)', 'head' : 'stns\&.2', 'pub' : 'MD2-21-ID-E', 'pg' : '1', 'autoscint' : '1'},
3     'orange-2\&.ls-cat\&.org' : { 're' : 'redis\\&.kvseq|stns\\&.2\\&.(\&.+)', 'head' : 'stns\&.2', 'pub' : 'MD2-21-ID-E', 'pg' : '1', 'autoscint' : '1'},
4     'venison\&.ls-cat\&.org'  : { 're' : 'redis\\&.kvseq|stns\\&.2\\&.(\&.+)', 'head' : 'stns\&.2', 'pub' : 'MD2-21-ID-E', 'pg' : '1', 'autoscint' : '1'},
5     'mung-2'              : { 're' : 'redis\\&.kvseq|stns\\&.1\\&.(\&.+)', 'head' : 'stns\&.1', 'pub' : 'MD2-21-ID-D', 'pg' : '1', 'autoscint' : '1'},
6     'mung-2\&.ls-cat\&.org'   : { 're' : 'redis\\&.kvseq|stns\\&.1\\&.(\&.+)', 'head' : 'stns\&.1', 'pub' : 'MD2-21-ID-D', 'pg' : '1', 'autoscint' : '1'},
7     'vidalia\&.ls-cat\&.org'  : { 're' : 'redis\\&.kvseq|stns\\&.1\\&.(\&.+)', 'head' : 'stns\&.1', 'pub' : 'MD2-21-ID-D', 'pg' : '1', 'autoscint' : '1'},
8 }
.fi
.PP
Definition at line 26 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.f 'HSETNX'"

.PP
Definition at line 633 of file mk_pgpmac_redis\&.py\&.
.SS "string mk_pgpmac_redis\&.fnc 'HSETNX'"

.PP
Definition at line 693 of file mk_pgpmac_redis\&.py\&.
.SS "mk_pgpmac_redis\&.hard_ini sys\&.argv[3]"

.PP
Definition at line 21 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.hard_ini_fields"
\fBInitial value:\fP
.PP
.nf
1 {
2     'active'          : ['Simulation', active_simulation],
3     'coord_num'       : ['CoordinateSystem', asis],
4     'largeStep'       : ['LargeStep', asis],
5     'maxPosition'     : ['MaxPosition', asis],
6     'minPosition'     : ['MinPosition', asis],
7     'motor_num'       : ['MotorNumber', asis],
8     'neutralPosition' : ['NeutralPosition', asis],
9     'precision'       : ['Precision', asis],
10     'smallStep'       : ['SmallStep', asis],
11     'u2c'             : ['UnitRatio', asis]
12     }
.fi
.PP
Definition at line 434 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.head sys\&.argv[1]"

.PP
Definition at line 13 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.hi \fBiniParser\&.iniParser\fP( \fBhard_ini\fP)"

.PP
Definition at line 589 of file mk_pgpmac_redis\&.py\&.
.SS "int mk_pgpmac_redis\&.i 0"

.PP
Definition at line 657 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.motor_dict"

.PP
Definition at line 257 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.motor_field_lists"

.PP
Definition at line 456 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.motor_num int( \fBmotor_dict\fP[m]['motor_num'])"

.PP
Definition at line 741 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.motor_presets"

.PP
Definition at line 497 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.p pi\&.get( section, 'MotorPosition')"

.PP
Definition at line 709 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.pi \fBiniParser\&.iniParser\fP( \fBpref_ini\fP)"

.PP
Definition at line 654 of file mk_pgpmac_redis\&.py\&.
.SS "dictionary mk_pgpmac_redis\&.plcc2_dict"
\fBInitial value:\fP
.PP
.nf
1 {
2     'omega'       : { 'status1' : 'M5001', 'status2' : 'M5021', 'position' : 'M5041'},
3     'align\&.x'     : { 'status1' : 'M5002', 'status2' : 'M5022', 'position' : 'M5042'},
4     'align\&.y'     : { 'status1' : 'M5003', 'status2' : 'M5023', 'position' : 'M5043'},
5     'align\&.z'     : { 'status1' : 'M5004', 'status2' : 'M5024', 'position' : 'M5044'},
6     'lightPolar'  : { 'status1' : 'M5005', 'status2' : 'M5025', 'position' : 'M5045'},
7     'cam\&.zoom'    : { 'status1' : 'M5006', 'status2' : 'M5026', 'position' : 'M5046'},
8     'appy'        : { 'status1' : 'M5007', 'status2' : 'M5027', 'position' : 'M5047'},
9     'appz'        : { 'status1' : 'M5008', 'status2' : 'M5028', 'position' : 'M5048'},
10     'capy'        : { 'status1' : 'M5009', 'status2' : 'M5029', 'position' : 'M5049'},
11     'capz'        : { 'status1' : 'M5010', 'status2' : 'M5030', 'position' : 'M5050'},
12     'scint'       : { 'status1' : 'M5011', 'status2' : 'M5031', 'position' : 'M5051'},
13     'centering\&.x' : { 'status1' : 'M5012', 'status2' : 'M5032', 'position' : 'M5052'},
14     'centering\&.y' : { 'status1' : 'M5013', 'status2' : 'M5033', 'position' : 'M5053'},
15     'kappa'       : { 'status1' : 'M5014', 'status2' : 'M5034', 'position' : 'M5054'},
16     'phi'         : { 'status1' : 'M5015', 'status2' : 'M5035', 'position' : 'M5055'}
17 }
.fi
.PP
Definition at line 35 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.plcc2_file open( '%s-plcc2\&.pmc' % (head), 'w')"

.PP
Definition at line 729 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.ppos pi\&.get( section, option)"

.PP
Definition at line 665 of file mk_pgpmac_redis\&.py\&.
.SS "mk_pgpmac_redis\&.pref_ini sys\&.argv[2]"

.PP
Definition at line 16 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.v \fBmotor_dict\fP[m]"

.PP
Definition at line 632 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.x pi\&.get( section, 'ScaleX')"

.PP
Definition at line 716 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.xlate \fBhard_ini_fields\fP[k]"

.PP
Definition at line 637 of file mk_pgpmac_redis\&.py\&.
.SS "tuple mk_pgpmac_redis\&.y pi\&.get( section, 'ScaleY')"

.PP
Definition at line 723 of file mk_pgpmac_redis\&.py\&.
.SS "list mk_pgpmac_redis\&.zoom_settings"
\fBInitial value:\fP
.PP
.nf
1 [
2     #lev   front  back  pos     scalex  scaley   section
3     [1,     4\&.0,   8\&.0,  34100, 2\&.7083,  3\&.3442, 'CoaxCam\&.Zoom1'],
4     [2,     6\&.0,   8\&.1,  31440, 2\&.2487,  2\&.2776, 'CoaxCam\&.Zoom2'],
5     [3,     6\&.5,   8\&.2,  27460, 1\&.7520,  1\&.7550, 'CoaxCam\&.Zoom3'],
6     [4,     7\&.0,   8\&.3,  23480, 1\&.3360,  1\&.3400, 'CoaxCam\&.Zoom4'],
7     [5,     8\&.0,  10\&.0,  19500, 1\&.0140,  1\&.0110, 'CoaxCam\&.Zoom5'],
8     [6,     9\&.0,  12\&.0,  15520, 0\&.7710,  0\&.7760, 'CoaxCam\&.Zoom6'],
9     [7,    10\&.0,  17\&.0,  11540, 0\&.5880,  0\&.5920, 'CoaxCam\&.Zoom7'],
10     [8,    12\&.0,  25\&.0,   7560, 0\&.4460,  0\&.4480, 'CoaxCam\&.Zoom8'],
11     [9,    15\&.0,  37\&.0,   3580, 0\&.3410,  0\&.3460, 'CoaxCam\&.Zoom9'],
12     [10,   16\&.0,  42\&.0,      0, 0\&.2700,  0\&.2690, 'CoaxCam\&.Zoom10']
13     ]
.fi
.PP
Definition at line 566 of file mk_pgpmac_redis\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
