.TH "mk_pgpmac_redis.py" 3 "Tue Jan 22 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mk_pgpmac_redis.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmk_pgpmac_redis\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.head\fP sys\&.argv[1]"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.pref_ini\fP sys\&.argv[2]"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.hard_ini\fP sys\&.argv[3]"
.br
.ti -1c
.RI "dictionary \fBmk_pgpmac_redis\&.motor_dict\fP"
.br
.ti -1c
.RI "dictionary \fBmk_pgpmac_redis\&.hard_ini_fields\fP"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.motor_field_lists\fP"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.bi_list\fP ['CryoSwitch']"
.br
.ti -1c
.RI "dictionary \fBmk_pgpmac_redis\&.motor_presets\fP"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.zoom_settings\fP"
.br
.ti -1c
.RI "tuple \fBmk_pgpmac_redis\&.hi\fP \fBiniParser\&.iniParser\fP( hard_ini)"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.v\fP motor_dict[m]"
.br
.ti -1c
.RI "string \fBmk_pgpmac_redis\&.f\fP 'HSETNX'"
.br
.ti -1c
.RI "tuple \fBmk_pgpmac_redis\&.pi\fP \fBiniParser\&.iniParser\fP( pref_ini)"
.br
.ti -1c
.RI "int \fBmk_pgpmac_redis\&.i\fP 0"
.br
.ti -1c
.RI "tuple \fBmk_pgpmac_redis\&.ppos\fP pi\&.get( section, option)"
.br
.ti -1c
.RI "string \fBmk_pgpmac_redis\&.fnc\fP 'HSETNX'"
.br
.ti -1c
.RI "tuple \fBmk_pgpmac_redis\&.b\fP pi\&.get( section, 'LightIntensity')"
.br
.ti -1c
.RI "tuple \fBmk_pgpmac_redis\&.p\fP pi\&.get( section, 'MotorPosition')"
.br
.ti -1c
.RI "tuple \fBmk_pgpmac_redis\&.x\fP pi\&.get( section, 'ScaleX')"
.br
.ti -1c
.RI "tuple \fBmk_pgpmac_redis\&.y\fP pi\&.get( section, 'ScaleY')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
