.TH "mk_pgpmac_redis.py" 3 "Mon Dec 24 2012" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mk_pgpmac_redis.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmk_pgpmac_redis\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBmk_pgpmac_redis\&.head\fP 'stns\&.2'"
.br
.ti -1c
.RI "dictionary \fBmk_pgpmac_redis\&.motor_dict\fP"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.motor_field_lists\fP"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.bi_list\fP ['CryoSwitch']"
.br
.ti -1c
.RI "dictionary \fBmk_pgpmac_redis\&.motor_presets\fP"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.zoom_settings\fP"
.br
.ti -1c
.RI "list \fBmk_pgpmac_redis\&.v\fP motor_dict[m]"
.br
.ti -1c
.RI "int \fBmk_pgpmac_redis\&.i\fP 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
