.TH "tagEthernetCmd" 3 "Wed Jan 23 2013" "LS-CAT PGPMAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagEthernetCmd \- 
.PP
PMAC ethernet packet definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pgpmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBRequestType\fP"
.br
.RI "\fIVR_UPLOAD or VR_DOWNLOAD\&. \fP"
.ti -1c
.RI "unsigned char \fBRequest\fP"
.br
.RI "\fIThe command to run (VR_PMAC_GETMEM, etc)\&. \fP"
.ti -1c
.RI "unsigned short \fBwValue\fP"
.br
.RI "\fICommand parameter 1\&. \fP"
.ti -1c
.RI "unsigned short \fBwIndex\fP"
.br
.RI "\fICommand parameter 2\&. \fP"
.ti -1c
.RI "unsigned short \fBwLength\fP"
.br
.RI "\fINumber of bytes in bData\&. \fP"
.ti -1c
.RI "unsigned char \fBbData\fP [1492]"
.br
.RI "\fIThe data buffer, if required\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
PMAC ethernet packet definition\&. 

Taken directly from the Delta Tau documentation\&. 
.PP
Definition at line 73 of file pgpmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char tagEthernetCmd::bData[1492]"

.PP
The data buffer, if required\&. 
.PP
Definition at line 79 of file pgpmac\&.h\&.
.SS "unsigned char tagEthernetCmd::Request"

.PP
The command to run (VR_PMAC_GETMEM, etc)\&. 
.PP
Definition at line 75 of file pgpmac\&.h\&.
.SS "unsigned char tagEthernetCmd::RequestType"

.PP
VR_UPLOAD or VR_DOWNLOAD\&. 
.PP
Definition at line 74 of file pgpmac\&.h\&.
.SS "unsigned short tagEthernetCmd::wIndex"

.PP
Command parameter 2\&. 
.PP
Definition at line 77 of file pgpmac\&.h\&.
.SS "unsigned short tagEthernetCmd::wLength"

.PP
Number of bytes in bData\&. 
.PP
Definition at line 78 of file pgpmac\&.h\&.
.SS "unsigned short tagEthernetCmd::wValue"

.PP
Command parameter 1\&. 
.PP
Definition at line 76 of file pgpmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LS-CAT PGPMAC from the source code\&.
